### ISSUE TITLE
Can not support to declare a registry at the top-level? (simple_switch)

### ISSUE THREAD

**Issue by MaoJianwei** [p4lang/p4c#906] opened 2017-09-15 02:01 UTC
Well, the manager of  p4lang/behavioral-model just said this is a compiler bug, and sent me here...

okay, As follow, it succeed to be compiled, but fail while running with simple_switch, and report:

```
mao@mao-vm:~/maoP4/testbmv2/techTest$ sudo simple_switch -L 'trace' --log-file ~/maoP4/mao.log --log-flush -i 0@ens192 -i 1@ens224 ~/maoP4/testbmv2/techTest/output.file
Thrift port was not specified, will use 9090
Calling target program-options parser
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted (core dumped)
mao@mao-vm:~/maoP4/testbmv2/techTest$
```

As the follow code, if I move _register<bit<8>>(10) maoReg;_ into ingress, it will works well.
Does it means that P4 can not support to declare registry at the top-level?

But if I want to share a register between ingress and egress, what should I do?

======== simplified code P4-16========

```
register<bit<8>>(10) maoReg;

control ingress(...) {

	//register<bit<8>>(10) maoReg;

    apply {

        if(hdr.ethernet.isValid()) {

            if(hdr.ethernet.etherType == 0x0806) {

            	bit<8> regVal;
                maoReg.read(regVal, 1);

                if(regVal > 3) {
                	regVal = 0;
                }

                maoReg.write(1, regVal + 1);
            }
        }
    }
}
```

**Comment by mbudiu-vmw** [comment] 2017-11-08 05:23
This seems to be a duplicate of #696.

**Comment by mbudiu-vmw** [comment] 2018-01-09 01:28
I will assume that this can be closed.

**Closed by mbudiu-vmw** 2018-01-09 01:28 UTC
Labels: bug, duplicate, fixed
