### ISSUE TITLE
header_union as a struct member

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4c#631] opened 2017-05-14 14:15 UTC
I can see that the compiler accepts header_union construct:
```
header_union layer4_t {
    icmp_t icmp;
    tcp_t  tcp;
    udp_t  udp;
}
```
But when I tried to put into the header struct,
```
struct my_headers_t {
    ethernet_t     ethernet;
    vlan_tag_t [2] vlan_tag;
    mpls_t [5]     mpls;
    arp_t          arp;
    arp_ipv4_t     arp_ipv4;
    ipv4_t         ipv4;
    layer4_t       layer4;
}
```
I got the following message:
```
l3_switch.p4(110): error: Type struct my_headers_t should only contain headers or header stacks
struct my_headers_t {
       ^^^^^^^^^^^^
```
Is it an oversight or not yet implemented?

**Comment by hanw** [comment] 2017-05-14 15:40
This is not yet implemented.

**Comment by mbudiu-vmw** [comment] 2017-05-14 15:57
There is an open issue about this, the union support in the back-ends is not yet implemented. This may be a front-end error, though.

**Comment by mbudiu-vmw** [comment] 2017-05-15 21:15
This seems to be a back-end bug, so then it is a duplicate of #561.

**Comment by mbudiu-vmw** [comment] 2017-05-23 20:58
I will close this one since we still have the one it duplicates.

**Closed by mbudiu-vmw** 2017-05-23 20:58 UTC
Labels: bug, duplicate
