### ISSUE TITLE
Add support for parser exceptions

### ISSUE THREAD

**Issue by cc10512** [p4lang/p4c#612] opened 2017-05-11 06:21 UTC
[l3_switch.p4.txt](https://github.com/p4lang/p4c/files/992008/l3_switch.p4.txt)

**Comment by mbudiu-vmw** [comment] 2017-05-11 15:24
This is a duplicate of #489.
The example provided is P4-16, and thus does not contain exceptions.
What is the connection to this issue?

**Comment by cc10512** [comment] 2017-05-11 15:56
Check the parse_ipv4 state. It calls verify() with an error code and expects the parser to throw an exception.

**Comment by mbudiu-vmw** [comment] 2017-05-11 15:58
There are no exceptions in P4-16; exceptions are a P4-14 concept.
The semantics in P4-16 is to just set an error and transition to reject. This feature is fully supported.

**Comment by mbudiu-vmw** [comment] 2017-05-11 16:41
I will close this since we already have a duplicate.
It would be nice to get a program with exceptions as a test case.

**Closed by mbudiu-vmw** 2017-05-11 16:41 UTC
Labels: duplicate
