### ISSUE TITLE
p4c-bm2-ss warns both with and without default action on table with action selector

### ISSUE THREAD

**Issue by tomrodeheffer** [p4lang/p4c#678] opened 2017-05-27 23:10 UTC
I wrote the following P4_16 program to check out the json for a table with action selector: [asel1.p4.txt](https://github.com/p4lang/p4c/files/1033853/asel1.p4.txt)
But p4c-bm2-ss complains about the default_action in the table:

    p4c-bm2-ss asel1.p4 -o out/asel1.json
    asel1.p4(31): warning: Target does not support default_action for tbl (due to action profiles)
        table tbl {
              ^^^

So I took out the default_action on that table, producing the P4_16 program: [asel2.p4.txt](https://github.com/p4lang/p4c/files/1033855/asel2.p4.txt)
But now p4c-bm2-ss complains that the table does not have a default_action:

    p4c-bm2-ss asel2.p4 -o out/asel2.json
    asel2.p4(31): warning: Table tbl does not have an `default_action' property
        table tbl {
              ^^^

It looks like there is no way to win this argument.  Fortunately, these messages are only warnings, and the bmv2 json is produced in either case, being identical except for things like source file and line number.  But there ought to be a way to write the P4_16 code so as to not generate any warnings.

**Comment by mbudiu-vmw** [comment] 2017-05-30 15:27
See issue #27: BMv2 does not support setting the default action for tables with action profiles.
I have just merged #653, which will remove the warning about the missing default_action, bringing the compiler in line with the spec. However, the other warning will still be there, because this feature is not really supported. So I will tag this issue as a duplicate of #27.

**Comment by mbudiu-vmw** [comment] 2017-10-11 05:52
Can we assume that this issue is fixed and can be closed?

**Closed** 2017-10-17 15:55 UTC
Labels: duplicate, fixed
