### ISSUE TITLE
Using bitshift on parsed data and using it to extract header containing varbit doesn't compile

### ISSUE THREAD

**Issue by kkaroly42** [p4lang/p4c#3527] opened 2022-09-12 22:42 UTC
I think I have discovered a bug whilst playing around with parsing TCP options.
When I try to parse a header containing a varbit and try to determine the length in the way you can see in my somewhat condensed example (uploaded as .txt, since .p4 is not a supported type), p4c doesn't give any error message but fails to produce a json file.  Replacing the varbit with bit or carrying out the bit shift earlier solves the problem.

Regardless, am I right in assuming that I should be able to do this and this should be considered a bug?
(This same code compiles without problem on the P4 Developer Day 2018 Spring Virtual Machine)

The exact command I used:
p4c --target bmv2 --arch v1model --std p4-16 bug.p4

[bug.txt](https://github.com/p4lang/p4c/files/9552218/bug.txt)

**Comment by mbudiu-vmw** [comment] 2022-09-12 23:11
I could not reproduce this problem, on my machine the latest version of the compiler produces a json file.

**Comment by mbudiu-vmw** [comment] 2022-09-12 23:12
I haven't checked whether the json file is correct, though

**Comment by kkaroly42** [comment] 2022-09-12 23:37
It might be the case that it was a bug up until v1.2.3.1. I just checked and since I was updating from the Ubuntu repository, I have 1.2.3.0 :). Sorry for not noticing the difference.

**Comment by mbudiu-vmw** [comment] 2022-09-21 19:36
If there is no reproduction I will close this. Feel free to reopen.

**Closed by mbudiu-vmw** 2022-09-21 19:36 UTC
Labels: invalid
