### ISSUE TITLE
Incorrect transformation in Predication pass

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#2345] opened 2020-04-27 21:25 UTC
With this version of p4c and the attached program, the Predication pass reorders some assignment statements in such a way that the final state is different than the original program will produce.
```
$ p4c --version
p4c 1.2.0 (SHA: d86cafa6)
```
It is possible that the root cause is the same as one of the other p4c issues, but I wanted to file this one separately, in case it has its own distinct root cause.  For example, this issue may be related: https://github.com/p4lang/p4c/issues/2330

Note: I did not write the test program.  It came from here: https://github.com/khooi8913/p4-op-in-condition/blob/e64e22b0d5b9b2f69cebe4700db869decc09cfb8/src/p4-xor-test.p4#L119

It was reported by the program's author on the P4 language Slack channel.  I will see if they will provide permission to add it as a test case to p4c.  If that does not work out, it should not be difficult to create another test program that produces similar behavior, I would guess.

[p4-xor-test.p4.txt](https://github.com/p4lang/p4c/files/4542111/p4-xor-test.p4.txt)

**Comment by khooi8913** [comment] 2020-04-28 05:00
Hi @jafingerhut, thanks for filing the issue! 

Feel free to use my program as a test case for p4c. 
I have also signed the ONF CLA as well. :)

**Comment by mbudiu-vmw** [comment] 2020-04-28 16:48
@matijasyrmia I will assume you will take a look at this one too.
Let us know if you are unable. Unfortunately it looks like I cannot formally assign it to you.

**Comment by matijasyrmia** [comment] 2020-04-29 08:05
@mbudiu-vmw I will see what is happening here, but I think it is related to #2330.

**Comment by fruffy** [comment] 2020-08-04 10:11
I can still reproduce this issue. In addition there seems to be another case that is distinct from this one. It is really tricky. 

The following program

```p4
action dummy(inout Headers val) {}
control ingress(inout Headers h) {
    action simple_action() {
        if (h.eth_hdr.eth_type == 1) {
            return;
        }
        h.eth_hdr.src_addr = 48w1;
        // this serves as a barrier
        dummy(h);
    }

    apply {
        h.eth_hdr.src_addr = 48w2;
        h.eth_hdr.dst_addr = 48w2;
        h.eth_hdr.eth_type = 16w2;

        simple_action();
    }
}
```
is transformed into

```p4
control ingress(inout Headers h) {
    bool hasReturned;
    ethernet_t val_eth_hdr;
    @name("ingress.simple_action") action simple_action() {
        hasReturned = false;
        {
            bool cond;
            cond = h.eth_hdr.eth_type == 16w1;
            hasReturned = (cond ? true : hasReturned);
        }
        {
            bool cond_0;
            cond_0 = !hasReturned;
            {
                val_eth_hdr = (cond_0 ? h.eth_hdr : val_eth_hdr); 
            }
            h.eth_hdr.src_addr = (cond_0 ? 48w1 : h.eth_hdr.src_addr); 
            h.eth_hdr = (cond_0 ? val_eth_hdr : h.eth_hdr);
        }
    }
    apply {
        h.eth_hdr.src_addr = 48w2;
        h.eth_hdr.dst_addr = 48w2;
        h.eth_hdr.eth_type = 16w2;
        simple_action();
    }
}
```
after `Predication`.

`cond_0` must be true because `eth_type` is `16w2`. With that in mind  `h.eth_hdr` will be **copied** into `val_eth_hdr`. After that, `48w` is assigned to `src_addr`. However, in the next step `val_eth_hdr` is copied back into `h.eth_hdr`. As far as I understand `val_eth_hdr` is a copy and is not affected by the modifications to `h.eth_hdr`. Which means that the original assignment is overwritten. 




[predication_with_inout_function_call.p4.txt](https://github.com/p4lang/p4c/files/5021474/predication_with_inout_function_call.p4.txt)

**Comment by mbudiu-vmw** [comment] 2020-08-04 18:49
@matijasyrmia can we assume you will take a look at this?

**Closed** 2021-06-28 23:15 UTC
Labels: bug
