### ISSUE TITLE
error: 4294967295: Value too large

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#1237] opened 2018-04-19 02:26 UTC
Compiling this program
```p4
header_type affairs {
  fields {
    flaccidly : 48;
    sleeting : 16;
  }
}

header_type backs {
  fields {
    sharps : 16;
    peptides : 16;
    whirs : 16;
    breasted : 16;
    browning : 16;
    jews : 32;
  }
}

header affairs kilometer;

header backs expressivenesss;

parser start {
  extract(kilometer);
  extract(expressivenesss);
  return ingress;
}

action mooneys() {
  subtract_from_field(expressivenesss.breasted, expressivenesss.peptides);
  subtract_from_field(kilometer.sleeting, 7);
}

table conceptualization {
  reads {
    kilometer : valid;
    kilometer.flaccidly mask 0 : lpm;
    expressivenesss : valid;
  }
  actions {
    mooneys;
  }
}

control ingress {
  apply(conceptualization);
}
```
using the p4c front-end produces the following mysterious error
```
p4test --std p4-14 allergically.p4 
error: 4294967295: Value too large
error: 4294967295: Value too large
error: 2 errors encountered, aborting compilation
```
If I delete "`mask 0`" from the `reads`, then there is no error.

**Comment by jafingerhut** [comment] 2018-04-19 04:57
Either someone has a program to pseudo-randomly generate P4 programs with an English dictionary for identifier names, or you are stretching P4 into domains it was never intended to go :-)

**Comment by cc10512** [comment] 2018-04-19 05:08
Are you saying that the value too large is not a bug but an allergic reaction? :)

**Comment by mbudiu-vmw** [comment] 2018-05-09 15:43
I think we can close this issue as well.

**Closed by mbudiu-vmw** 2018-05-09 15:43 UTC
Labels: bug, fixed
