### ISSUE TITLE
BMv2 back end: Duplicate objects of type 'header' with name 'h' 

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#3620] opened 2022-10-25 13:30 UTC
Triggered by #3605.

`gauntlet_action_mux-bmv2.p4` fails because of an issue in BMv2 compiler back end (?). Running an STF test produces the output: 

```
Calling target program-options parser                                                        
Duplicate objects of type 'header' with name 'h' 
```
It looks like the compiler produces an incorrect JSON: 

```json
"headers" : [
  {
    "name" : "scalars",
    "id" : 0,
    "header_type" : "scalars_0",
    "metadata" : true,
    "pi_omit" : true
  },
  {
    "name" : "standard_metadata",
    "id" : 1,
    "header_type" : "standard_metadata",
    "metadata" : true,
    "pi_omit" : true
  },
  {
    "name" : "eth_hdr",
    "id" : 2,
    "header_type" : "ethernet_t",
    "metadata" : false,
    "pi_omit" : true
  },
  {
    "name" : "h",
    "id" : 3,
    "header_type" : "H",
    "metadata" : false,
    "pi_omit" : true
  },
  {
    "name" : "h",
    "id" : 4,
    "header_type" : "H",
    "metadata" : false,
    "pi_omit" : true
  }
],
```

**Comment by jfingerh** [comment] 2022-10-25 14:38
It appears that the occurrence of `h` as a field in both the struct headers and the user-defined metadata struct is not a case that the p4c BMv2 back end currently handles.  More generally, any field with a common name between those two structs probably causes problems.

**Comment by mbudiu-vmw** [comment] 2022-10-28 23:00
The sad thing is that we have a pass RenameUserMetadata which is supposed exactly to fix this, but it turns out to do nothing (you can just comment it out and you get the same result).

**Comment by jfingerh** [comment] 2022-11-19 15:51
@mbudiu-vmw In this comment https://github.com/p4lang/p4c/pull/3653#issuecomment-1302375948 on PR #3653 you said:

"It should be easy to create a reproduction by having a metadata and a header structure with a common field name."

The test program `gauntlet_action_mux-bmv2.p4` _does_ have a common field name `h` in user-defined metadata and in the user-defined header struct.

Before PR #3653 was merged, the behavior in creating the BMv2 JSON file is as described in the original comment creating this issue.

After PR #3653 was merged, the BMv2 JSON file is different.  p4c-bm2-ss now creates one field in the `"headers"` section of the BMv2 JSON file named `h`, and another one named `userMetadata.h`.

If you have ideas on how to create a test P4 program that recreates this issue after PR #3653 was merged, I'm curious to hear what they are.  It isn't obvious to me.

**Comment by mbudiu-vmw** [comment] 2022-11-21 18:30
That is interesting. So perhaps the pass that assigns new names actually works, but not for all programs. This is the most frequent source of problems in the compiler: forgetting that the IR is a DAG and not a tree. The fix may be as simple as adding a visitDagOnce = false. Let me submit a PR for that purpose.

**Closed** 2022-11-21 21:06 UTC
Labels: bug, fixed, bmv2
