### ISSUE TITLE
Why a different error message for some 'complex' assignment left hand sides?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#2150] opened 2020-01-23 15:03 UTC
While developing test programs for the PR that aims to add support for run-time variable indexes to header stacks https://github.com/p4lang/p4c/pull/2139 we came across a kind of odd difference in some error messages that seem to indicate that some run-time variable index assignments are treated quite a bit differently in the compiler internals, and we were wondering if this is a sign of a limitation of the current compiler internals, and/or imply that adding this feature fully generally will require different kinds of changes than have been included in that PR so far.

For example, in the attached test program, an assignment like this:
```
hdr.vector[hdr.ml.idx1].e =
            hdr.ethernet.dstAddr[47:40];
```
causes the latest p4c code as of 2020-Jan-22 using the command `p4c filename.p4` to give an error message "hdr.ml.idx1: Invalid all array indexes must be constant".  The only place in the p4c code that contains the string "all array indexes must be const" is the file p4c/backends/bmv2/common/expression.cpp, so that error message is issued from the bmv2 back end code.

The above is expected.  No problem there.

However, if you make the left hand side more complex, like this:
```
        hdr.vector[hdr.vector[hdr.ethernet.dstAddr[2:0]].e].e =
            hdr.ethernet.dstAddr[47:40];
```
and run `p4c filename.p4`, you get a different error message:
```
runtime-index-4-bmv2.p4(121): [--Werror=type-error] error: Expression [].e cannot be the target of an assignment
        hdr.vector[hdr.vector[hdr.ethernet.dstAddr[2:0]].e].e =
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
The only error message containing the string "cannot be the target of an assign" occurs in file: p4c/frontends/p4/typeChecking/typeChecker.cpp, so this message is caught in a completely different way, and in a part of the code where there are existing test cases for doing things like attempting to assign a value to an `in` parameter, or to the name of an extern object, or a few other kinds of things that are completely illegal in the language, whereas I thought the expression above is legal.

The same expression gives no error or warning message at all when you run `p4test filename.p4` instead of `p4c filename.p4`.

Any idea what the difference is here?  Should it be giving a different error message, or should it be the same "all array indexes must be constant" even for the more complex assignment?

[runtime-index-4-bmv2.p4.txt](https://github.com/p4lang/p4c/files/4103676/runtime-index-4-bmv2.p4.txt)

**Comment by mbudiu-vmw** [comment] 2020-01-23 18:20
The error still happens in the bmv2 back-end, after an expression lowering pass is run.
You can see where an error happens by running the compiler with -v.
The type-checker is run almost before every pass.
You probably want this case as a test case for the non-constant array index PR. It may be that the lowering pass does not handle all legal expressions.

**Comment by hesingh** [comment] 2020-01-23 19:03
Indeed it is the `LowerExpressions` pass.  Let me look at its code and see what is going on.

```
hemant@ubuntu:/tmp/p4c/build$ ./p4c-bm2-ss --std p4-16 ../testdata/p4_16_samples/runtime-index-2-bmv2.p4 -o tmp.json -v
PassManager_7_LowerExpressions
../testdata/p4_16_samples/runtime-index-2-bmv2.p4(78): [--Werror=type-error] error: Expression [].e cannot be the target of an assignment
        hdr.vector[hdr.vector[hdr.ethernet.dstAddr[39:32] & 0x7].e & 0x7].e =
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by hesingh** [comment] 2020-01-23 19:56
When this expression is used as array index, `hdr.ethernet.dstAddr[39:32] & 8w0x7`, the error happens.  If the expression is replaced by, say, a zero index, the code compiles.  The LowerExpressions pass handles Slice which is part of the runtime index used.  But other arithmetic in `& 8w0x7` is something the  pass does not handle.

**Comment by hesingh** [comment] 2020-01-23 20:19
Another thought.  

Just like the p4c frontend and midend code has let the runtime index untouched and let the backend deal with it, the bmv2 backend's LowerExpressions could do the same.  But how do we get the pesky TypeChecking error to go away?  After all, the behavioral-model supports runtime index as Right-value of assignment for quite sometime.  I reversed the P4 statement for left- and right- values in assignment and then no error happens.  This is the statement that passes p4c-bm2-ss compiling. 

`hdr.ethernet.dstAddr[47:40] = hdr.vector[hdr.vector[hdr.ethernet.dstAddr[39:32] & 0x7].e & 0x7].e;`

Either we elide this code segment of code

https://github.com/p4lang/p4c/blob/master/frontends/p4/typeChecking/typeChecker.cpp#L3366

or extend the code segment to check if expression has array index and array index is runtime, let typeChecking pass.

**Comment by hesingh** [comment] 2020-01-23 21:33
@jafingerhut You should be a happy camper.  This issue is fixed with the latest checkin to the runtime index PR.

**Comment by jafingerhut** [comment] 2020-01-23 21:56
@hesingh Always nice if a feature added to the compiler doesn't have strange corner cases that do not work :-)

**Comment by hesingh** [comment] 2020-01-23 22:00
@jafingerhut I can't thank you enough to generate nasty and corner cases in P4 programs for features developed for p4c.

**Comment by mbudiu-vmw** [comment] 2020-01-24 18:14
I will promote this into a bug, with the attached simpler reproduction which gives an error using p4c-bm2-ss.
```
#include <v1model.p4>

typedef bit<48> mac_addr_t;

header ethernet_t {
    mac_addr_t dstAddr;
    mac_addr_t srcAddr;
    bit<16>    etherType;
}

header vec_e_t {
    bit<8> e;
}

struct headers {
    ethernet_t ethernet;
    vec_e_t[8] vector;
}

struct metadata_t {
}

parser MyParser(packet_in packet, out headers hdr, inout metadata_t meta,
                inout standard_metadata_t standard_metadata) {
    state start {
	transition accept;
    }
}

control ingress(inout headers hdr, inout metadata_t meta,
                inout standard_metadata_t standard_metadata) {
    apply {
        hdr.vector[hdr.vector[hdr.ethernet.dstAddr[39:32] & 0x7].e & 0x7].e =
            hdr.ethernet.dstAddr[47:40];
    }
}

control egress(inout headers hdr, inout metadata_t meta,
               inout standard_metadata_t standard_metadata) {
    apply {}
}

control MyVerifyChecksum(inout headers hdr, inout metadata_t meta) {
    apply {}
}

control MyComputeChecksum(inout headers hdr, inout metadata_t meta) {
    apply {}
}

control MyDeparser(packet_out packet, in headers hdr) {
    apply {
        packet.emit(hdr);
    }
}

V1Switch(MyParser(), MyVerifyChecksum(), ingress(), egress(),
         MyComputeChecksum(), MyDeparser()) main;
```

**Comment by mbudiu-vmw** [comment] 2020-01-24 18:51
This was indeed caused by a bug in the lowering pass which was updating the typemap manually, but forgetting to mark expressions that are left-values properly.

**Closed** 2020-01-28 22:53 UTC
Labels: bug, fixed
