### ISSUE TITLE
Inlining functions and duplicate table calls

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2344] opened 2020-04-27 09:10 UTC
This is a really niche issue I stumbled across on accident but I thought I might still file it. I have not been able to reproduce this with other declarations, only with undefined headers.

When calling a table twice, `RemoveActionParameters` may not always maintain the isolation of variable declarations. 

In this case 

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    @name("ingress.simple_action") action simple_action() {
        {
            bool hasReturned = false;
            bit<32> retval;
            H tmp1_0;
            if (tmp1_0.a != 32w10) {
                tmp1_0.a = tmp1_0.a + 32w10;
            }
            hasReturned = true;
            retval = tmp1_0.a;
            h.h.a = retval;
        }
    }
    @name("ingress.simple_table") table simple_table_0 {
        key = {
            h.h.b: exact @name("key") ;
        }
        actions = {
            simple_action();
            @defaultonly NoAction_0();
        }
        default_action = NoAction_0();
    }
    apply {
        simple_table_0.apply();
        simple_table_0.apply();
    }
}
```
turns into 

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    bool hasReturned;
    bit<32> retval;
    H tmp1_0;
    @noWarn("unused") @name(".NoAction") action NoAction_0() {
    }
    @name("ingress.simple_action") action simple_action() {
        {
            hasReturned = false;
            if (tmp1_0.a != 32w10) {
                tmp1_0.a = tmp1_0.a + 32w10;
            }
            hasReturned = true;
            retval = tmp1_0.a;
            h.h.a = retval;
        }
    }
    @name("ingress.simple_table") table simple_table_0 {
        key = {
            h.h.b: exact @name("key") ;
        }
        actions = {
            simple_action();
            @defaultonly NoAction_0();
        }
        default_action = NoAction_0();
    }
    apply {
        simple_table_0.apply();
        simple_table_0.apply();
    }
}
```
where `tmp1_0` may be set by the previous table call and influence the execution of the second call, despite being defined inside the action body.
No stf test because the simple switch does not supported multiple table calls just yet. 

[two_tables.p4.txt](https://github.com/p4lang/p4c/files/4538605/two_tables.p4.txt)

**Comment by mbudiu-vmw** [comment] 2020-04-28 16:46
I would not say that this is a bug - the original program reads an undefined value, and what happens from that point on is undefined; this behavior is a legal one.

**Comment by fruffy** [comment] 2020-04-28 19:00
How about this one then:

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    @name("ingress.simple_action") action simple_action() {
        {
            bool hasReturned = false;
            bit<32> retval;
            H tmp1_0;
            if (!tmp1_0.isValid()) {
                tmp1_0.setValid();
                tmp1_0.a = 32w10;
            } else {
                tmp1_0.a = tmp1_0.a + 32w15;
            }
            hasReturned = true;
            retval = tmp1_0.a;
            h.h.a = retval;
        }
    }
    @name("ingress.simple_table") table simple_table_0 {
        key = {
        }
        actions = {
            simple_action();
        }
        default_action = simple_action();
    }
    apply {
        simple_table_0.apply();
        simple_table_0.apply();
    }
}
```
is turned into

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    bool hasReturned;
    bit<32> retval;
    H tmp1_0;
    @name("ingress.simple_action") action simple_action() {
        {
            hasReturned = false;
            if (!tmp1_0.isValid()) {
                tmp1_0.setValid();
                tmp1_0.a = 32w10;
            } else {
                tmp1_0.a = tmp1_0.a + 32w15;
            }
            hasReturned = true;
            retval = tmp1_0.a;
            h.h.a = retval;
        }
    }
    @name("ingress.simple_table") table simple_table_0 {
        key = {
        }
        actions = {
            simple_action();
        }
        default_action = simple_action();
    }
    apply {
        simple_table_0.apply();
        simple_table_0.apply();
    }
}
```

Initially, the result is 10, but after it is 25. I tried to avoid undefined behaviour, at least I think I did.

**Comment by mbudiu-vmw** [comment] 2020-04-28 19:46
This isn't any different, according to the spec the value of the tmp1_0 variable is undefined if you don't initialize it explicitly.

**Comment by jafingerhut** [comment] 2020-04-28 20:00
Doesn't the spec require that variables with a header type are at least guaranteed to have valid be false?  Section 7.2.2 "Header types" says 'When a header is created its “validity” bit is automatically set to false.'

**Comment by fruffy** [comment] 2020-04-28 20:01
So explicit initialization here means `H tmp1_0 = {0}`? So
```
H tmp1_0;
if(tmp1_0.isValid()) {
    tmp1_0.setValid();
    tmp1_0 = {0};
}
```
is not explicit? My assumption was a freshly declared header is invalid, if it is not initialized.

**Comment by mbudiu-vmw** [comment] 2020-04-28 20:03
Then we should fix the section 10.2 of the spec, which claims otherwise.
I think that we have a pass which should handle this case.

**Comment by mbudiu-vmw** [comment] 2020-04-28 20:11
We have a pass called ResetHeaders which does exactly this: it sets all declared headers to invalid.
However, it does this only in parsers. So if we decide that uninitialized headers are invalid in controls too then it's very easy to extend this functionality.

**Comment by jafingerhut** [comment] 2020-04-28 22:38
It seems bringing up in the LDWG to verify the intended behavior here.  I will create a p4-spec issue to remind us.

The pass called ResetHeaders: does it make all 'global to a single parser or control' headers invalid at the beginning of execution of the parser or control?  If so, then there is still some potential trickiness or work to ensure that all headers declared local in some block, function, action, etc. are all initialized invalid, too.  In particular, this issue shows that the compiler can currently take a local variable inside of a single action, make it "global to a control", and ideally it should have all local initializations performed on each call to the action, not only once for the entire control.

**Comment by mbudiu-vmw** [comment] 2020-04-28 22:48
Yes, this transformation is done relatively eary - certainly before inlining.
Can you please add a line to the wiki too?

**Comment by jafingerhut** [comment] 2020-04-28 23:27
Issue created here: https://github.com/p4lang/p4-spec/issues/845

Yes, I will add a line to the P4 LDWG wiki page linking to that issue.

**Comment by mbudiu-vmw** [comment] 2020-04-28 23:28
I have marked this as a bug: it's either a bug in the compiler or in the spec.

**Comment by mbudiu-vmw** [comment] 2021-05-28 23:47
According to the new spec clarifications, this is now a bag in the compiler.

**Closed** 2021-06-08 17:21 UTC
Labels: bug, fixed, question
