### ISSUE TITLE
Compiler Bug: visitor returned non-Statement type: <Vector<StatOrDecl>>(104016) !!!

### ISSUE THREAD

**Issue by MaoJianwei** [p4lang/p4c#887] opened 2017-09-08 03:22 UTC
The attach is my P4-16 source code, please help me! Thank you!

[mao_mpls_switch.p4.zip](https://github.com/p4lang/p4c/files/1286658/mao_mpls_switch.p4.zip)

mao@mao-vm:~/maoP4/testbmv2/newtry$ p4c-bm2-ss --p4v 16 --p4runtime-file maoRuntime.file --p4runtime-format text -o output.file mao_mpls_switch.p4 
**In file: /home/mao/maoP4/p4c/ir/visitor.cpp:457
Compiler Bug: visitor returned non-Statement type: <Vector<StatOrDecl>>(104016)**

mao@mao-vm:~/maoP4/testbmv2/newtry$

**Comment by hanw** [comment] 2017-09-09 04:25
Here is a simplified program that reproduces the problem.
```
#include <core.p4>
#include <v1model.p4>

header mpls {
    bit<8> label;
}

struct my_packet {
  mpls[8] data;
}

struct my_metadata {}

parser MyParser(packet_in b, out my_packet p, inout my_metadata m, inout standard_metadata_t s) {
  state start {
    transition accept;
  }
}

control MyVerifyChecksum(in my_packet hdr, inout my_metadata meta) {
    apply { }
}

control MyIngress(inout my_packet p, inout my_metadata m, inout standard_metadata_t s) {
    apply { }
}

control MyEgress(inout my_packet p, inout my_metadata m, inout standard_metadata_t s) {
    apply { }
}

control MyComputeChecksum(inout my_packet p, inout my_metadata m) {
    apply { }
}

control MyDeparser(packet_out b, in my_packet p) {
    apply {
        if (p.data[0].isValid()) {
            b.emit(p.data);
        }
    }
}

V1Switch(MyParser(), MyVerifyChecksum(), MyIngress(), MyEgress(), MyComputeChecksum(), MyDeparser()) main;
```

**Comment by hanw** [comment] 2017-09-09 04:26
Without the `if` statement, the error does not happen.

```
control MyDeparser(packet_out b, in my_packet p) {
    apply {
            b.emit(p.data);
    }
}
```

**Comment by MaoJianwei** [comment] 2017-09-09 04:35
Yes, i known that while debuging last night, but I wish compiler will give clear introductions for syntax checking  :)

**Comment by jafingerhut** [comment] 2017-09-09 04:37
In this program, the 'if' is redundant because emit() does nothing if the header(s) you give it are invalid.  For a header stack it should only emit the subset of headers in the stack that are valid.

That said, agreed that the compiler should not crash, and preferably give a clear error message.

**Comment by MaoJianwei** [comment] 2017-09-09 04:46
Hi, jafingerhut

I don't think 'if' is redundant, because the header maoMpls may be valid.

I wonder if packet.emit() will check the validation of header_stack internally? 
If I emit() an invalid header_stack without the beforehand 'if' check, will the program crash?

**Comment by hanw** [comment] 2017-09-09 04:54
`if` statement is allowed in the deparser, the error message should be fixed.

That said, the semantics of emit() function is: it will check the validity of each header in the header_stack, and only emit the valid headers. You can check section 14.1 in P4-16 spec.

**Comment by mbudiu-vmw** [comment] 2017-10-04 06:11
This should be fixed, so I will close it.

**Closed by mbudiu-vmw** 2017-10-04 06:11 UTC
Labels: bug, fixed
