### ISSUE TITLE
Recirculation does not always copy metadata

### ISSUE THREAD

**Issue by edgar-costa** [p4lang/p4c#1669] opened 2019-01-16 14:29 UTC
This applies to `resubmit` and probably to `clone` (Did not try).

Metadata fields are not copied to the recirculated packet unless you copy the entire metadata struct or you create a tuple of individual fields. For example if you have:

```
struct metadata_t {
   bit<8> count;
}
struct metadata { 
    metadata_t meta1;
    metadata_t meta2;
}
```
The metadata will be copied in the following cases:
```
recirculate(meta);
recirculate({meta.meta1.count, meta.meta2.count});
```
However, I remember (and just tested) that with older versions of bmv2/p4c copying only some structs from the main metadata worked. And the following does not work anymore:
```
recirculate(meta.meta1);
recirculate({meta.meta1, meta.meta2});
```

Is this a bug or it's an intended behaviour ? I personally think that the previous way made it quite easier, for example when you want to copy an entire structure that has 10s of fields.

**Comment by mbudiu-vmw** [comment] 2019-01-16 17:20
Can you elaborate on what "does not work" mean?
Can you supply a complete program and an STF file with input/output packets that exhibits this problem?

**Comment by jafingerhut** [comment] 2019-01-16 17:34
Yes, a complete program exhibiting the problem would be helpful, if you are able to share one.

Just a wild guess that the symptoms you describe sound similar to this issue: https://github.com/p4lang/p4c/issues/1479

which I closed because the root cause seems to be this one: https://github.com/p4lang/p4c/issues/1514

**Comment by edgar-costa** [comment] 2019-01-16 17:40
By saying "does not work" I am talking about the main issue. The metadata fields do not get copied. Something that did work 3-4 months ago. 

I will update the program with the problem so to be fast (but i did not include any STF file..)

[issue1669.txt](https://github.com/p4lang/p4c/files/2765402/issue1669.txt)

If you run it with a bmv2 with debugging enabled you can see that the counter I track will be always 0, whereas if you recirculate using: `recirculate({meta.count_struct.counter});` (line 137 which is commented), the metadata field will be copied and thus the counter will increase.

**Comment by jafingerhut** [comment] 2019-01-16 17:47
At least with the version of p4c I tried compiling that program with (the latest source code as of 2019-Jan-09), using the command `p4c --target bmv2 --arch v1model issue1669.p4` (after renaming it to issue1669.p4), I looked at the BMv2 JSON, and the parameter to the recirculate operation there had been constant-propagated by the compiler to be a hard-coded value of 0x1, not a reference to the variable `meta.count_struct.counter`.  BMv2 JSON neither complains about such BMv2 JSON files, nor will it preserve a metadata field that it does not know the name of in the recirculate operation.

This looks like the same behavior as reported in #1479 to me.

**Comment by edgar-costa** [comment] 2019-01-16 17:56
Sorry for making you rename the file... but github did not let me update `.p4`  extensions. 

Not sure if useful, but I can tell you that with a bmv2 from 2018-11-Sep and p4c from 2018-06-Sep this was not happening.  

By the way, note that in the example in which this does not work I am recirculating the entire struct:  `recirculate(meta.count_struct);` and not the counter. When using the counter it does get copied.

**Comment by jafingerhut** [comment] 2019-01-16 18:01
Someone like @mbudiu-vmw knows much better than I exactly what changes to p4c might change the results here, from one commit to the next.  As another wild guess, recent changes involving flattening structs in internal front/mid-end passes of the compiler could perhaps have caused the change in behavior you are seeing.

The root cause is #1514, which means that the current implementation of all of the operations resubmit, recirculate, clone, and clone3 in P4_16 programs, when asked to preserve metadata, is very fragile to precisely what optimizations the compiler makes in your particular source program.

**Comment by hesingh** [comment] 2019-01-16 18:16
It one would like to disable the recently developed flatten midend passes, please edit your backend's midend.cpp to remove the .h files and the flatten passes.  Rebuild p4c and see if you still see the error. 

For example, remove the following lines (and relevant .h files) from ```p4c/backends/bmv2/simple_switch/simple_switch```

```
new P4::FlattenHeaders(&refMap, &typeMap),
new P4::FlattenInterfaceStructs(&refMap, &typeMap),
```

**Comment by jafingerhut** [comment] 2019-01-16 18:22
Thinking about this particular example program a little bit more, there could be a "chicken and egg" optimization problem with p4c here.

It is replacing an occurrence of `meta.count_struct` with a constant, based on the assumption that the field is initially 0.  It is always 0, when a new packet arrives, but it can be non-0 precisely if/when a packet is resubmitted, recirculated, or cloned while preserving this metadata field from an earlier processing pass.

So the compiler is optimizing assuming the initial value of 0, _in a program that specifically is asking for the value to be preserved for some packets_.

A more conservative approach by the compiler would be to _never_ assume that the initial values of metadata are 0.  That would hinder optimizations when no recirculate/resubmit/clone operations are done by a program, I know, so it isn't the ideal solution.

**Comment by mbudiu-vmw** [comment] 2019-01-16 21:57
The metadata is an `in` parameter, so it can have any value the environment chooses to give it.
We cannot assume it to be 0 ever.

**Comment by mbudiu-vmw** [comment] 2019-01-16 22:00
@jafingerhut : I think that 1 is the id of the field list describing the fields that are recirculated. So there is no constant folding.

**Comment by mbudiu-vmw** [comment] 2019-01-16 22:04
The json generated looks fine to me.

**Comment by jafingerhut** [comment] 2019-01-16 22:35
Wow.  Sorry if I completely messed up my analysis of this issue above.  Let me take a closer look.

**Comment by jafingerhut** [comment] 2019-01-16 23:09
OK, the BMv2 JSON does not have the problems I indicated above.  It does generate a field_list, and refer to that field_list in the recirculate primitive operation, as Mihai said.  Thanks for the correction to my mistake there, Mihai.

Attaching the issue1669.json.txt file that I generated using the version of `p4c` generated from the latest source code as of 2019-Jan-09.

However, the field_list in the BMv2 JSON file that is used by the recirculate primitive contains only a temporary variable generated somewhere in the compiler or its bmv2 back end, I don't know where, which is _not_ the original metadata field that the recirculate operation in the P4_16 source code says should be preserved.

It is as if this code:
```
recirculate({meta.count_struct});
```
is being replaced by the compiler with this code:
```
bit<8> tmp = meta.count_struct.counter;
recirculate({tmp});
```
That preserves the value of `tmp` across the recirculate operation, but does _not_ preserve the value of `meta.count_struct.counter` across the recirculate operation.

In the attached file issue1669.json.txt, search for `"field_lists"` to see the definition of the one field_list there, and search for `"recirculate"` to see the one recirculate operation in there, and the `assign` statement just before it that does the copying to `tmp` described above.
[issue1669.json.txt](https://github.com/p4lang/p4c/files/2766452/issue1669.json.txt)

**Comment by jafingerhut** [comment] 2019-01-16 23:12
It still seems to me that the root cause issue is #1514 -- the mismatch between P4_14 field_lists being explicitly represented in BMv2 JSON, as "references" or "names" of things, vs. the p4c P4_16 compiler treating the last operand to recirculate and similar operations as a list of current values.

**Comment by mbudiu-vmw** [comment] 2019-01-16 23:43
I guess recirculation was never really implemented properly. It was a coincidence that it was working.

**Comment by mbudiu-vmw** [comment] 2019-01-16 23:50
This is not really the same as #1514, at least not as the problem is described in #1514. There are two different issues here:
- the resubmit/recirculate is done at the end
- these operations also *write* to metadata in the beginning of the pipeline

The first issue is easy to solve in p4-16 by keeping a copy of the data.
The second one is harder; it does not really match the semantics of P4-16.

**Comment by mbudiu-vmw** [comment] 2019-01-17 00:00
Here is one way this could be done, although it's not as pretty as the p4-14 solution.

We add a function `recirculate_receive<T>(out T data);` to v1model.p4. This function must be invoked first thing in the start state of the parser if the user wants to recirculate. It copies the data that is recirculated in the specified values. The user can call `recirculate<T>(in T data)` anywhere. The compiler checks that the two types T must be the same. However, the fields sent and received can be different. The compiler will make sure to compile this to an implementation that bmv2 can support.

The compiler will generate this code for p4-14 programs, so these should be automatically taken care of.

**Comment by mbudiu-vmw** [comment] 2019-01-17 00:07
The same treatment will have to be performed for resubmit. We could reuse the same function to receive, we could call it `metadata_receive` instead, assuming that one cannot do both resubmit and recirculate.

**Comment by hesingh** [comment] 2019-01-17 00:12
Maybe change ```metadata_receive``` to ```recycle_receive```.  I am used to a router data plane that uses a recycle queue for more packet processing.

**Comment by edgar-costa** [comment] 2019-01-17 00:12
But are all these changes really needed? (saying it from the ignorance). But, this used to work few months ago. 

Adding that `metadata_receive` would require a change in all the P4 programs that use resubmit and recirculate, in the spec, and does not seem very intuitive to newcomers.

**Comment by mbudiu-vmw** [comment] 2019-01-17 00:43
Not for p4-14 programs, only for p4-16 programs.
It was working by accident.

**Comment by jafingerhut** [comment] 2019-01-18 03:58
There is no need for a recirculate_receive operation in order to make recirculate work for P4_16 that I can see, because v1model makes metadata an `inout` parameter to the ingress parser.
```
parser Parser<H, M>(packet_in b,
                    out H parsedHdr,
                    inout M meta,
                    inout standard_metadata_t standard_metadata);
```
BMv2 JSON can already assign values to fields of `meta` when a packet is resubmitted or recirculated.

The reason why this bug was filed is because BMv2 JSON is being told the wrong names of fields to preserve (auto-generated temporary names, not user-defined names).

**Comment by jafingerhut** [comment] 2019-01-18 04:03
I guess I should say that I can see a way that potentially a new recirculate_receive operation _could_ assist in making recirculate work in P4_16+v1model and preserve metadata.  However, if you want it to handle an arbitrary subset of fields of the `meta` Parser parameter, it seems like that is already implemented for you in BMv2 JSON, but only if the names of the fields given match the names of the fields in `meta`.  No fields outside of `meta` and `standard_metadata` need to be supported (because the P4_14 spec says that you cannot specify packet header fields in the list of fields to preserve for resubmit, recirculate, or clone, if I recall correctly).

**Comment by mbudiu-vmw** [comment] 2019-01-18 17:43
This is an important problem, so we should solve it in a good way. I will post several messages.
First, P4 is designed such that one can "substitute equals for equals" without changing the meaning of a program. That means that from the compiler point of view the following are always equivalent, irrespective of the context:
```
void f(in bit value);

f(x);
```

and

```
bit tmp = x;
f(tmp);
```

As such, you can see why the compiler does not implement `recirculate` in the way you would expect.

**Comment by mbudiu-vmw** [comment] 2019-01-18 17:44
The way recirculate is used in p4-14 is really "call-by-name", where the name that is passed as an argument is important. In P4-16 we only have copy-in/copy-out, which is a form of call-by-value really. The name does not matter, only the value.

**Comment by mbudiu-vmw** [comment] 2019-01-18 17:46
There are two ways to implement the semantics of recirculate from p4-14. The first one is to do explicit reading of values from the outside world in the parser, and an explicit writing of values to the outside world in egress. So the P4-14 program

```
recirculate(f);
```

Would be translated to

```
void recirculate_input<T>(out T data);

parser p() {
    state start {
        recirculate_input(f);
        ...
    }
}

control egress() {
    apply {
       recirculate(f);
    }
}
```

**Comment by mbudiu-vmw** [comment] 2019-01-18 17:50
The second alternative is the way PSA does it: you have an additional metadata struct for recirculated data.

```
// architecture file
parser p<H, M, R>(out Headers h, inout M user_metadata, in R recirculated_metadata, inout standard_metadata) {
  // you can access the recirculated metadata at anytime
}

control egress<H, M, R>(..., out R recirculated_metadata, ...) {
  // you recirculate just by writing something to the recirculated_metadata, and perhaps calling recirculate() with no arguments
}
```

We can actually implement this solution in v1model as well, by providing an alternate definition of the switch architecture which has one more argument in each of the blocks. If the user wants to recirculate they will have to instantiate the architecture with recirculated metadata. Otherwise they can continue to use the old V1Switch.

**Comment by mbudiu-vmw** [comment] 2019-01-18 17:52
I am only interested in solutions which do not break any of the existing P4-14 and P4-16 programs. We can make both of these work with a little more work in the p4-14->p4-16 translator and the simple_switch back-end. Please chime in with proposals and comments.

**Comment by jafingerhut** [comment] 2019-01-18 20:39
I cannot yet think of a strong motivation for one of the two approaches you describe over the other.

The more PSA-like one would presumably also need additional arguments for resubmit metadata, and clone metadata, with extra parameters for each one?  In that case, yes, it does start to look like PSA, and a potential advantage of that is that it gets the compiler and BMv2 that much closer to implementing PSA.

Perhaps one way to generate comments/discussion is to add this to the agenda for the next language design work group meeting, and be sure potential attendees are aware of the size of the change this could represent.

**Comment by jafingerhut** [comment] 2019-01-19 23:56
Mihai, in earlier comments you say these things: 'P4 is designed such that one can "substitute equals for equals" without changing the meaning of the program', which I think is intended to mean "substitute _expressions_ for other _expressions_ as long as those expressions evaluate to equal values".  I suspect this gets into technical areas of programming language semantics which I am not fully educated on to discuss, but doesn't that conflict with "call-by-name" semantics?

Perhaps a more concrete way of asking the question is: "Does p4c compile P4_14 programs that use field lists 'by accident' rather than 'by design', because p4c's implementation assumes throughout that expressions can be substituted for other expressions if they have equal values?"

**Comment by jafingerhut** [comment] 2019-01-21 04:52
If you get the now-latest version of repository https://github.com/p4pktgen/p4pktgen it includes an updated version of the Python program tools/bmv2-json-check.py that will warn about the following kinds of problems in a BMv2 JSON file that you give it as a command line argument:

Any recirculate, resubmit, or clone operation that references a field list that contains one of the following kinds of fields _in the BMv2 JSON file_ (the P4 source program is not used to determine this at all):

+ a field_list element that is a constant value, which could happen because of a constant value in the field_list in the source program, or because p4c used constant propagation to replace a named metadata field with a constant.
+ a field_list element that is a header field, which the P4_14 spec says is not supported.  I checked with a small test P4_14 program, and it gives no error or warning message if you attempt to do a resubmit operation with a field_list containing a packet header field.
+ a field_list element that has a name where the header name begins with "scalar" and the field name begins with "tmp".  That is a heuristic check, not a guarantee, that the variable is a compiler-generated temporary name, but it seems to work fairly often and catch such things.

BMv2 simple_switch itself does not seem to make any such checks, and silently accepts such BMv2 JSON files.

**Comment by jafingerhut** [comment] 2019-01-21 20:15
I do not know if this is error-prone nonsense of an idea, or not, but perhaps one way to correctly compile the P4_14 field lists, at least in the cases when they are used in recirculate, resubmit, and clone operations, is to create special "name reference" objects in the compiler, that are only equal to themselves, and thus no equal-for-equal substitutions are possible for them?

There is no need to do this for field lists used in other contexts that I know of, e.g. digest message generation, or checksum/hash calculation, because in those cases it really is the value of the fields that matters, not the name references.

**Comment by mbudiu-vmw** [comment] 2019-01-21 21:38
There is no such construct in p4-16. If we want to write recirculate in p4-16 we have to do it within the language.

**Comment by jafingerhut** [comment] 2019-01-21 22:57
I agree that what I spoke about in my last couple of comments here are not needed for p4-16.

Is it worth a separate issue to consider it for using p4c as a p4-14 compiler?

**Comment by mbudiu-vmw** [comment] 2019-01-21 23:19
The compiler converts all p4-14 programs to p4-16. We want to deprecate p4-14, so we must be able to do this for all p4-14 programs.

**Comment by mbudiu-vmw** [comment] 2019-01-23 21:14
I am trying to prototype a fix. I am looking at the v1model-special-ops-bmv2.p4 program that @jafingerhut wrote. This program recirculates the standard metadata. It looks to me like this should not be legal in general - the standard metadata is set by the environment and it describes the packet that is being processed. You should not be able to alter it arbitrarily.

**Comment by mbudiu-vmw** [comment] 2019-01-23 21:17
If this assumption is correct, and we can only recirculate user metadata, then we may have an even simpler way to implement recirculation in v1model: the user adds an annotation on the metadata fields which have to be recirculated. When calling the `recirculate()` function - with no arguments - these fields are automatically recirculated. We don't need to change anything in the v1model.

**Comment by mbudiu-vmw** [comment] 2019-01-23 21:19
`struct user_metadata {
    bit<32> a;
    @recirculate
    bit<32> b;
}

...
control egress(... user_metadata u, ...) {
    apply {
        recirculate(); // recirculates the labeled fields
    }
}
```

**Comment by mbudiu-vmw** [comment] 2019-01-23 21:24
BTW: we could do the same trick to the PSA, simplifying its definition.
Note that the semantics would be closer to the P4-14 implementation, since recirculation would be done with the values at the END of the egress pipeline. In fact, calling `recirculate()` merely sets a flag to cause the recirculation to happen.

I like this alternative, it looks very simple.

**Comment by jafingerhut** [comment] 2019-01-23 21:36
I agree that perhaps a P4 program should be prohibited from attempting to preserve standard/intrinsic metadata on a recirculate/resubmit/clone operation.  At the very least, enabling it would seem to require specifying _which_ fields could be preserved, and which could not, because preserving a field like instance_type that is intended to indicate whether a received packet was recirculated, resubmitted, or is new, sounds very error prone to put into the hands of the programmer.

Mihai, it sounds like what you are proposing is that for a P4_14 program with multiple resubmit operations, the user must only be allowed to specify one field_list, not a different field_list for each of the operations?

Or that when translating a P4_14 program with multiple different field_list's used by different resubmit operations, that the compiler will auto-translate that to a P4_16 program that specifies preserving the union of all fields in all such field_lists?

Others should add their feedback to such an idea, besides me, but my first reaction on hearing the idea is that it does simplify things for the programmer, at the potential cost of making it more difficult for the compiler to minimize the amount of state that must be preserved for a packet.  The P4_14 and PSA approaches allow the programmer to help the compiler minimize such state, if they are willing to go to the effort of specifying multiple field_lists (for P4_14) or multiple independent sets of state to preserve (in PSA).

**Comment by mbudiu-vmw** [comment] 2019-01-23 21:43
Yes, the compiler would compute the union.
I don't think this is necessarily more wasteful in practice - in hardware implementations you have to allocate "wires" (or packet header slots) to carry any field the user may want, even if you do not carry these fields in all recirculate operations. If you multiplex fields on the same wires (or packet header slots) then you have to generate circuitry to demultiplex as well.

Moreover, I expect most programs will have 1 recirculate/resubmit/clone call in the entire program.

@jafingerhut : maybe if you have some time you can help craft a test case like the one you already wrote but which recirculates only user metadata.

**Comment by jafingerhut** [comment] 2019-01-23 21:49
Mihai, another thought on your idea -- For P4_16 programs, recirculate goes from egress back to ingress, and the ingress and egress user-defined metadata can be defined independently, and in general need not have any field names in common.  I agree it is likely good coding practice not to name the same value with multiple different names when you can easily make them the same, but in terms of your proposal, unless we require the names of preserved fields to match between ingress and egress user-defined metadata, the annotations you propose do not contain enough information to specify the desired preservation behavior.

That is an issue at least for recirculate (from egress, back to ingress), and ingress-to-egress clone (the other direction).

**Comment by mbudiu-vmw** [comment] 2019-01-23 22:30
I actually think this is not a real problem. In general, if a field is not recirculated its value will be garbage. So you will just get more fields than expected in some cases, but you probably will ignore them. The same argument applies to using the union of the fields. 
We could also have two different annotations: `@recirculate` and `@resubmit`, but I also think that in practice one will be sufficient. A field can have any number of annotations.
Finally, we could also define the semantics of `recirculate()` to recirculate all of the user metadata if there are no annotations at all.

**Comment by hesingh** [comment] 2019-01-23 22:35
I have conversed with a few P4 customers and they tell me, do not use any annotation in the P4 program unless there is no alternative.   The backend has to be intelligent.  Thus, I would design explicit data structs, flags, and use the API's for clone, clone3, resubmit etc. to track input user metadata.  For a general case, where ingress and egress user metadata are defined independently, the pipeline design (section 4 of P4-16 spec) ties the two together.  

```
control pipeX (user_metadata ingress_m, user_metadata egress_m, ...) {
}
 ```

**Comment by jafingerhut** [comment] 2019-01-23 22:38
Mihai, suppose the ingress user-defined metadata and egress user-defined metadata in a P4_16 PSA arch program are _completely different_, and you put @recirculate annotations on 5 of the fields in each of them.  How is the compiler supposed to match up the 5 egress fields to the 5 ingress fields?  By field name?

**Comment by mbudiu-vmw** [comment] 2019-01-23 22:46
You will get 10 fields in both cases. But in each case they will include the 5 you care about.

**Comment by mbudiu-vmw** [comment] 2019-01-23 22:48
But, as I said, if we want fine-grained control we can have 2 different annotations.
In v1model there is only one user metadata definition for all blocks.

**Comment by mbudiu-vmw** [comment] 2019-01-23 22:53
For PSA we have to take a look. The way it's done now is just fine too.

**Comment by mbudiu-vmw** [comment] 2019-01-23 22:59
We can just leave PSA as it is. It seems to support everything that is needed.
It is also easier to understand how it works.

**Comment by mbudiu-vmw** [comment] 2019-01-23 22:59
So I take back my comment on 10 fields above, that applies to v1model.

**Comment by jafingerhut** [comment] 2019-01-23 23:33
Created PR https://github.com/p4lang/p4c/pull/1693 that removes standard_metadata from the P4_16 test program that currently preserves it across resubmit/recirculate/clone3 operations.  It appears that I wrote the program so that the only thing it is relying on being preserved are the packet contents, and that the standard_metadata.instance_type is _not_ preserved, but filled in as it should be to indicate whether the packet was recirculated, resubmitted, cloned, or none of those (e.g. a new packet arriving on a port).

I can look into creating a separate test case that _relies_ for correct operation on preserving one or more user-defined metadata fields.  Perhaps I will make it a P4_14 program, since at least then I know how to write the source code to follow the spec, and should continue working no matter how we change these operations for P4_16+v1model

**Comment by mbudiu-vmw** [comment] 2019-01-24 16:32
I think this is the same bug as https://github.com/p4lang/p4c/issues/1694

**Comment by jafingerhut** [comment] 2019-01-24 16:47
P4_16 + v1model does not use an intrinsic_metadata header, and yet resubmit still works in BMv2 JSON today for the v1model-special-ops.p4 and stf test program, so I do not understand how they can be the same bug?

**Comment by mbudiu-vmw** [comment] 2019-01-24 16:55
If you are lucky the compiler does not use temporaries for the data you want to recirculate, so it works as you expect. I hope we are talking about the same problem.
Isn't "standard_metadata" the same as what p4-14 calls "intrinsic metadata"?

**Comment by jafingerhut** [comment] 2019-01-24 17:10
The example P4_14 program for issue #1694 can be compiled with today's p4c, and if you examine the BMv2 JSON file, there is a normal, un-mangled standard_metadata_t header_type, and a mangled intrinsic_metdata_t header_type.  These are separate header_types in BMv2's implementation.  I do not know the history here, but both standard_metadata_t and intrinsic_metadata_t contain fields that are "defined by the architecture", but for some probably-historical implementation reason they were put into separate headers.  Similarly for queueing_metadata_t, which is yet another separate header containing additional fields for use in P4_14 programs.  You can see documentation for P4_14 programmers using simple_switch here, which I wrote some of, but Antonin reviewed it all, so hopefully it is correct according to today's BMv2: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

**Comment by cc10512** [comment] 2019-01-30 05:12
Sorry to join the party so late, and more over to throw a monkey wrench into the whole discussion.
In my view, recirc and resubmit are such fundamental operations that it seems they have to have proper support in the language, rather than annotations. Sure, we can define externs for them (functions or objects) that capture the required semantics, just as we did in PSA. However, there were numerous discussions on how do we preserve the "call-by-name" semantics of P4-14, and the only solution we came up with is to leave it to programmers to invoke these extern functions in the deparser. Note that I would very much prefer to have the language support for call-by-reference for field lists. I know it is not an easy change and will require significant discussion for acceptance, but I think we should at least consider it.

Computing the union of all the fields or even recirculating the entire set is not a realistic option. Think about a scenario where you recirculate to implement a state machine that transitions from one type of processing to another and needs to consume data. If you have to maintain the whole set for every packet that is recirculated, you're likely to not make progress. The support for multiple field lists for both recirculation and resubmit is not negotiable -- any solution we devise has to do it, and it is better to have the language support to distinguish between the different instances. Otherwise we're just making life more difficult for both users, who will be confused on what data they get because they expect only a subset, and for us because we need to do magic to disentangle the different instances (based on ... not sure what).

So, I am afraid this is one of those cases where we have to accept that we made a mistake in simplifying the language a bit too much and go back and re-think a better design. 

@jnfoster, you've been very quiet on this thread. Will you please chime in?

**Comment by hesingh** [comment] 2019-01-30 14:24
With so many comments, it's hard to figure out all goals and non-goals of this work.  It would be good to write a short doc and attach it to this issue.  For example, have we agreed that ingress and egress user metadata is disjoint, because then we need to find a solution.  Maybe this goal is no longer a goal.  

I have already said, I don't like using Annotations.

**Comment by jnfoster** [comment] 2019-02-03 16:49
I am indeed weighing into this conversation late. 

As a strawman, let's consider the simplest possible design, which is motivated by what many hardware targets really do. We could arrange things so that `recirculate`, `resubmit`, etc. don't actually do anything special to the headers and user-defined metadata -- they merely set a flag in the intrinsic metadata that causes the packet to take a non-standard processing path in the architecture, and indicates that it has done so. In this view, any data that needs to be "wormholed" along with the packet, needs to be handled explicitly by the programmer using the deparser and parser. For example, the programmer could define a header type to hold the recirculated data, make sure it is `valid` at the end of the pipeline in question so it will be `emit`tted by the deparser, and then check for the flag and `extract` it in the parser.

What's non-optimal about this solution?

1. We lose the ability to "recirculate" data from anywhere in the pipeline. I'm not sure if this is a feature or a bug. Consider a program that calls `recirculate(meta)` and later in the same pipeline executes `meta.f = 0`. Which value of `meta` will be used? If the latter, it would be better in my opinion not to provide the illusion of being able to call `recirculate` anywhere since its effects take place later.

2. The programmer has to go to the trouble of defining a header type to store the recirculated data, this type needs to be flexible to store *all* different kinds of data that might be recirculated (maybe unions or overlays help), and most critically, they need to handle it explicitly in the deparser/parser! This is a bit silly since the data is really just being internally routed across the P4 device, and the compiler could very well handle the (de)serialization code automatically, just like it does for intrinsic metadata.

I agree with Calin that if this is an important feature in practical programs, relying on annotations to get a non-standard semantics (if that's what is being proposed) seems like the wrong strategy -- we should add new constructs that make common uses of this use case convenient.

If my analysis is right, could people weigh in on which of the two issues above is most critical? To recap: (i) being able to invoke `recirculate` and friends from anywhere in a `control` or (ii) automating the encoding/deparsing/parsing of this data? Or both!

If we understand the requirements, and have some example programs, then I think we can make progress towards a good solution.

And to focus attention on the issues, let's declare v1model and P4_14 translator a non-goal for the moment. We need to fix that too, but let's get the P4_16 design right first.

**Comment by jafingerhut** [comment] 2019-02-03 17:56
I don't see anything wrong with your analysis.  I think your strawman proposal sounds fairly close to what PSA proposes for these operations, except that it uses structs instead of headers for containing the data to be carried with a packet when it is recirculated, resubmitted, or cloned.  It does require explicit assignments in the deparser and parser to make sure this data gets copied to the right output parameter in the deparser, and copied from the right input parameter in the parser.

Here is some sample P4_16 + PSA arch code for copying the data from a parser input parameter named recirc_meta into a place the user chose to put it in, during parsing: https://github.com/p4lang/p4-spec/blob/master/p4-16/psa/examples/psa-example-recirculate.p4#L94-L109

and here is the portion of the egress deparser code that copies the desired data to be recirculated into the PSA-defined output parameter: https://github.com/p4lang/p4-spec/blob/master/p4-16/psa/examples/psa-example-recirculate.p4#L191-L193

There are similar example programs `psa-example-resubmit.p4` and `psa-example-clone-to-port.p4` that show similar code examples for resubmit and clone cases, and also `psa-example-bridged-metadata.p4` which gives a demo of PSA's _explicit_ method for doing the corresponding thing for indicating which metadata is carried from ingress to egress for normal unicast and multicast packets, which is _not_ P4_14's "everything is carried along if you use it in egress".

I am _not_ saying that PSA is the only way to go -- there are design choices there that could be made different in a different design, certainly.  The design choices in PSA are, I believe, based on an explicit embracing of P4_16's "no spooky action at a distance", i.e. all function/control/action/extern calls take effect immediately, with the values the parameters have at the time of the call, not some later time.

I wouldn't be surprised if we could add some kind of early pass to a P4_16 compiler that adds field lists and delayed evaluation of the values of fields in the field list, and even auto-generated code similar to PSA for marshaling and demarshaling metadata to be carried with packets.  The 'output' language of this compiler pass could be something like today's P4_16+PSA arch.  The 'input' language could be something that has more P4_14-like constructs that make it more convenient for programmers.

**Comment by mbudiu-vmw** [comment] 2019-02-03 18:02
The annotations do not change the semantics of p4-16, they merely describe how the environment of he program behaves.

Mihai

________________________________

**Comment by jnfoster** [comment] 2019-02-03 18:04
Sure, in a narrow sense. They do change the way an operation supported on a
specific standard architectures behaves... one that Calin is arguing is
central enough to many programs that we should give it first-class support.

**Comment by jafingerhut** [comment] 2019-02-05 02:46
Nate, I think you mentioned this during the language design WG meeting earlier today (2019-Feb-04), but wanted to point out that the P4_14 language spec explicitly says that you can do resubmit(meta), but it is not the current values of the fields of `meta` that are preserved, but the final values those fields have at the end of ingress processing.  Thus later assignments during ingress processing to meta.f _are_ kept.

**Comment by jafingerhut** [comment] 2019-07-12 02:12
An update on the status of this issue.

The recirculate, resubmit, and clone operations should all work as of the latest versions of p4c and behavioral-model simple_switch, but only if you give them an empty list of metadata fields to preserve.

As state in this issue and follow-up discussions, p4c and simple_switch will in some cases correctly preserve a non-empty list of fields given to these operations, but due to the way this is implemented, it is an accident that it sometimes works, not by design.  Some optimization passes in p4c can make changes to the intermediate form of the code, such that the generated BMv2 JSON compiler output files does _not_ preserve the metadata fields the P4 program specified in the source code.

There has been a fair amount of discussion in the P4 language design work group on the issue, and several possible approaches considered to change the v1model architecture definition so that these operations could be done in a way that consistently preserves such metadata fields.  None of them have desirable enough properties that they are considered worth implementing, at least not yet.  Someone may still come up with another approach considered good enough, but we do not have one now.

The long term goal is to implement the PSA architecture for P4_16, which uses a different way to specify the preserved metadata for these operations, and also to implement automatic translation of P4_14 programs to P4_16+PSA architecture programs that have the same behavior as the original program, or at least differ only in well-documented ways.

In the mean time, this change will likely be merged into p4c soon: https://github.com/p4lang/p4c/pull/2000

If it is merged, p4c will issue a warning if the source program uses any of these operations with a non-empty list of fields to preserve.  There is no such warning if the list of fields to preserve is empty, as that works fine.  The output BMv2 JSON files will not be altered by that change.  If a particular source P4 program happens to work with today's p4c and simple_switch, they will continue to work after that change, but with the warning printed.  If a particular source P4 program happens not to work with today's p4c and simple_switch, it will still not work after that change, and with the warning printed.

Note that only the P4_16 v1model architecture is affected by this.  Other P4_16 architectures may choose to implement similar operations in a different way than the v1model architecture does within p4c and simple_switch -- check with your P4 tool vendor.

**Comment by jafingerhut** [comment] 2019-07-13 00:02
As one more reference to add for those who may want to learn of proposals considered, here is a write-up of several of the ideas, with code examples, and a discussion of some of the known advantages and disadvantages of each: https://github.com/jafingerhut/p4-guide/blob/master/v1model-special-ops/README-resubmit-examples.md

**Comment by vitor-l** [comment] 2020-06-05 18:13
Hello, @jafingerhut! 

I'm joining this discussion a little bit late, but I would like to know if it is still necessary to use empty list of metadata fields when using _recirculate_ with _clone_. If so, how am I supposed to save any data in the P4-16?

**Comment by jafingerhut** [comment] 2020-06-05 19:43
@vitor-l The compiler will let you use non-empty lists of metadata fields to preserve on all of the operations resubmit, recirculate, and clone.  It will warn that this is not supported, but even while warning, it _may_ just happen to implement it correctly.  It might also implement it incorrectly.  It is a case by case basis, and the most precise advice I have on telling whether it compiled in a way that will preserve metadata correctly is given in this documentation: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md#hints-on-distinguishing-when-metadata-is-preserved-correctly

**Comment by jafingerhut** [comment] 2020-06-05 19:44
Long term there appear to be some people now actively working to get the open source Portable Switch Architecture (PSA) implementation fully implemented, and it should have a reliable way to preserve metadata for these operations that matches well with the P4_16 language.

**Comment by castilhorosa** [comment] 2020-09-16 00:15
Hello guys!

I'm also joining in the discussion a little late.. I'm trying to use the PSA architecture to recirculate packets keeping metadata, according to psa spec, just to avoid the problems aforementioned. When I try to compile the program though, I get the following error: "target bmv2-psa not yet implemented.". Is there any update in fully support PSA on BMv2 since May 2019, as was asked here: http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2019-May/003943.html ?

**Comment by jafingerhut** [comment] 2020-09-16 02:32
There has been active work on enhancing the open source PSA implementation over the last several months by several volunteers.  The status of some features that are working, with test P4 programs that are passing their tests, can be found here: https://github.com/jafingerhut/p4-guide/tree/master/psa-test-info

Unfortunately, while recirculation, resubmit, unicast, multicast, and ingress-to-egres cloning are all working, they are working only when you do not attempt to preserve user-defined metadata.  That feature is still yet to be implemented, and requires changes to the p4c back end code, and likely also to the behavioral-model bmv2 code.

The list of tests I mentioned above should be kept up to date as more features are working, if you want to check there, but feel free to ask again.  We will also be making an announcement when a few more features are working, on the p4-dev email list and a few other places, and again when the work has been completed (or at least almost all of them).

**Comment by castilhorosa** [comment] 2020-09-16 21:39
Thanks @jafingerhut .  I've been trying to find a temporary solution to solve my problem. Once is not possible yet to keep user-defined metadata when recirculating packets in PSA, is it possible to copy what I want into a header, make that header valid, recirculate the packet with such header by emitting it in egress deparser, and then recovery it in ingress parser? Or the only way I can copy data into a header is by using the exctract() function in ingress/egress parser? I'm assuming that P4 allows me to add new headers into packets at runtime. Correct me if I'm wrong. If this naivly approach works, I could use the information from the header and make it invalid afterwards. I was not able to find that information in PSA spec.

**Comment by jafingerhut** [comment] 2020-09-16 23:11
@castilhorosa Yes, you should be able with today's PSA implementation to recirculate packets, but add new headers to the packet before it recirculates.  Such new headers could be added in the egress deparser.  They could alternate be added in the ingress deparser if you wished, as long as you realize they would be visible to your egress parser code, too.

You can also have ingress parser code that does something like this, to parse packets differently when they are recirculated, versus newly arriving packets:
```
transition select (istd.packet_path) {
    PSA_PacketPath_t.RECIRCULATE: parse_recirculated_packet;
    default: parser_non_recirculated_packet;
}
```

**Comment by mbudiu-vmw** [comment] 2021-06-29 21:24
It looks like this is one of these wontfix issues.

**Closed** 2021-06-29 21:25 UTC
Labels: bug, wontfix
