### ISSUE TITLE
The BMv2 back-end cannot set default_actions for tables

### ISSUE THREAD

**Issue by mbudiu-bfn** [p4lang/p4c#27] opened 2016-04-27 17:59 UTC
The problem is that BMv2 does not yet support setting the default actions.

**Comment by mbudiu-vmw** [comment] 2017-03-25 02:19
@antoninbas @sethfowler 
Is this issue still an issue?

**Comment by antoninbas** [comment] 2017-03-25 20:09
yes tables with action profiles still don't have default actions in bmv2, for now they still use default members / groups.

**Comment by mbudiu-vmw** [comment] 2017-10-11 05:51
It looks like this is by design, so I am closing this issue.

**Closed by mbudiu-vmw** 2017-10-11 05:51 UTC
Labels: bmv2, bug, wontfix
