### ISSUE TITLE
STF files for several tests seem to use incorrect syntax

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#961] opened 2017-10-04 06:29 UTC
All are p4_14 programs, named like counter*.p4 and gateway*.p4

**Comment by jafingerhut** [comment] 2017-11-09 20:32
I tried with recent versions of p4c and behavioral-model repos to run commands like this, to run individual STF tests:
```
% cd p4c/build
% ../backends/bmv2/run-bmv2-test.py .. -b -v ../testdata/p4_14_samples/gateway1.p4
```
For the 8 files gateway1.p4 through gateway8.p4 in the p4_14_samples directory, I found no STF syntax errors.  gateway1.p4 through gateway4.p4 ran STF tests that failed, because there were different number of actual vs. expected output packets.  Perhaps this was masked before some recent changes that caused STF tests to do more precise checking of actual vs. output packets?

gateway5.p4 through gateway8.p4 had no syntax errors in the STF files, and all tests passed, so no problems seen there.

Perhaps for gateway1.p4 through gateway4.p4, the best thing to do is to update the STF files to have the correct sequence of expected output packets, checking the new ones by hand to verify they are correct?

**Comment by jafingerhut** [comment] 2017-11-09 20:40
I also tried the command mentioned in the previous comment for p4_14_samples/counter1.p4 through counter5.p4.

All of them had STF syntax errors for lines like these:
```
wait
check_counter ...
```
Those look like commands intended to read counters and verify that they had particular values.  Those commands are not implemented in STF, but it appears that a syntax error on any line causes STF tests to just report them as a syntax error, and continue reading more lines looking for correct ones, so no real harm done other than maybe making people think these tests cover more than they actually do, and that those STF commands are implemented.

One option would be to enhance STF tests to implement those commands, but my impression is that the trend for such testing of other APIs like reading counters might be towards using PTF rather than STF, or whatever it is that P4 Runtime API testing is doing?

All of the tests for counter1.p4 through counter4.p4 failed in my attempts.  Only counter5.p4 passed.

The quickest thing I can think of doing would be to delete the STF lines that are not implemented, eliminating the syntax error warnings, and update the STF files for counter1.p4 through counter4.p4 to pass, probably by updating the expected output packets in the STF files.  Sound like a reasonable action to take?

**Comment by ChrisDodd** [comment] 2017-11-09 20:41
Some of the tests fail because bmv2 outputs (to port 0) packets that never
have their egress_spec set, instead of dropping them as the test expects...

**Comment by jafingerhut** [comment] 2017-11-09 20:46
@ChrisDodd Do you think that behavior of sending a packet to output port 0 should be considered a bug to be fixed in p4c and/or behavioral-model code?

Or perhaps it should be considered expected behavior and the STF tests updated to expect the packets that are currently coming out?

**Comment by mbudiu-vmw** [comment] 2017-11-09 21:11
The Python script that parses the stf file silently reads some lines that it actually cannot parse.
I believe that these stf files are used to test other back-ends, which are not public. There is a private script somewhere which can understand the extended STF syntax, but the extended syntax has not been brought into the public scripts. We are waiting for someone to extend our public parser.

Even if we don't implement support for the check_counter commands, we should have support for the table population commands; then these tests would succeed.

**Comment by cc10512** [comment] 2017-11-09 21:16
We can contribute the lexer/parser code, but at the moment, we do not have the bandwidth to integrate it with the run-bmv2 script. If there is someone who can do that, I can open a PR later this week.

**Comment by mbudiu-vmw** [comment] 2017-11-09 21:23
Note that the stf python script already has a very rudimentary parser, which could also be extended.
I estimate the amount of work required to about 1/2 day.
But it probably would be nicer to use a more full-featured one.

**Comment by jafingerhut** [comment] 2017-11-09 21:41
@mbudiu-vmw In my reading of the output of these STF tests, the public version of the STF parser _is_ parsing the add_table commands correctly, and installing table entries into bmv2 before sending packets.  Do you see something that leads you to believe otherwise?

**Comment by mbudiu-vmw** [comment] 2017-11-09 21:44
I believe that this line: 
`add tab1 ethernet.dstAddr:0xa1a2a3a4a5a6 act(port:2) = A`
is parsed incorrectly; the `= A` part is not handled by the parser. This causes the entry not to be added to the table correctly, which in turn causes the packet not to be output on port 2, which in turn causes the test to fail.

The syntax `= A` is a handle to the entry, which can be used in a `check_counter` statement to retrieve the associated direct counter.

**Comment by mbudiu-vmw** [comment] 2017-11-09 21:44
The parser does not emit any error.

**Comment by jafingerhut** [comment] 2017-11-09 21:59
Got it.  Didn't notice the "= A" part in counter1.stf.  Deleting those from counter1.p4 (but leaving the rest of the "add tab1" line) causes the test to add the table entries to bmv2, but the actual vs. expected output packets still differ, for reasons I haven't dug into yet.

Is it expected that there is much value in extending STF's capabilities here, vs. using something besides STF?

**Comment by mbudiu-vmw** [comment] 2017-11-09 22:00
We have invested significantly in stf for testing the compiler. Another method would probably involve significant work for converting all our tests. We are open to any proposals.

**Comment by ChrisDodd** [comment] 2017-11-09 22:10
Arguably it is unspecified in the P4_14 spec what happens to a packet that neither has egress_spec set nor has an explicit drop() called on it.  So probably the tests should be fixed to not depend on it.

**Comment by jafingerhut** [comment] 2017-11-09 22:34
@ChrisDodd Makes sense.  I can maybe come up with some proposed changes for the tests that are failing only because of that reason for review, and leave for later the ones that depend upon reading counters.

**Comment by jafingerhut** [comment] 2017-11-10 16:05
I opened this PR https://github.com/p4lang/p4c/pull/1031

It updates the gateway1.p4 through gateway4.p4 programs so that they cleanly drop packets unless they match a later table entry that causes them to be sent to a port, and the existing STF tests pass with those changes, so it appears like they were written with an assumption in mind that this is how the P4 programs should behave.

I see Calin has opened a PR that adds code that can parse STF files with a larger set of STF statements supported, but haven't looked at the details yet of how to use that.

**Closed** 2017-11-28 00:50 UTC
Labels: bug, fixed
