### ISSUE TITLE
Compiler Bug: Null name

### ISSUE THREAD

**Issue by qin-nz** [p4lang/p4c#1001] opened 2017-11-01 10:22 UTC
Using the follwing p4 code and compile by `p4c-bm2-ss --p4v 16 "mapswitch.p4" -o "mapswitch.p4.json"`
[bug1.zip](https://github.com/p4lang/p4c/files/1433776/bug1.zip)

```
In file: /home/dy/p4c/backends/bmv2/expression.cpp:268
Compiler Bug: /home/dy/p4c/backends/bmv2/expression.cpp:268: Null name
```
https://github.com/p4lang/p4c/blob/fc30c9538ef8ea3f1eee6015a1e61d54908f627c/backends/bmv2/expression.cpp#L263-L268

I found three ways to avoid compiler bug:
- delete line 70 in parser.py `meta.arp_dst_ipv4 = p.arp_ipv4.tpa;`
or 
- delete line 14 in ingress.py `clone3<map_meta_t>(ctype, CPU_MIRROR_SESSION, meta_for_clone);`
or
- delete line 12 in ingress.py and use `meta` instead of  local variable `meta_for_map` in line 13-14.

line 68-72 in parser.py
```
    state parse_arp_ipv4 {
        b.extract(p.arp_ipv4);
        meta.arp_dst_ipv4 = p.arp_ipv4.tpa;
        transition accept;
    }  
```

line 11-15 in ingress.py
```
    action copy_to_cpu(bit<16> reason, CloneType ctype){
        map_meta_t meta_for_clone;
        meta_for_clone.cpu_reason = reason;
        clone3<map_meta_t>(ctype, CPU_MIRROR_SESSION, meta_for_clone);
    }
```

**Comment by mbudiu-vmw** [comment] 2017-11-02 17:15
Here is a much smaller program which reproduces the bug:
```
#include <core.p4>
#include <v1model.p4>

struct Headers {}

struct Meta {
    bit b;
}

parser p(packet_in b, out Headers h, inout Meta m, inout standard_metadata_t sm) {
    state start {
        m.b = m.b + 1;
        transition accept;
    }
}

control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    Meta x;

    action a() {
        x.b = 1;
        clone3<Meta>(CloneType.I2E, 32w64, x);
    }

    table t {
        key = { sm.egress_spec: exact; }
        actions = { a(); }
    }

    apply {
        t.apply();
    }
}

control vrfy(inout Headers h, inout Meta m) { apply {} }
control update(inout Headers h, inout Meta m) { apply {} }
control egress(inout Headers h, inout Meta m, inout standard_metadata_t sm) { apply {} }
control deparser(packet_out b, in Headers h) { apply {} }

V1Switch(p(), vrfy(), ingress(), egress(), update(), deparser()) main;
```

**Comment by mbudiu-vmw** [comment] 2017-11-02 17:17
@hanw : the bug happens because ConvertHeaders::init_apply visits the header type M and adds it to the list visited_headers. When later the code is supposed to allocate space for the m.b field of the metadata in `addTypesAndInstances` this type is skipped, since it is already in the map.

Since you (re)wrote this code I will assign the bug to you, but if you don't plan to address is soon I will handle it.

**Comment by hanw** [comment] 2017-11-02 17:24
I will handle this one.

**Comment by mbudiu-vmw** [comment] 2017-11-20 17:11
I will close this one because it looks like it is fixed.

**Closed by mbudiu-vmw** 2017-11-20 17:11 UTC
Labels: bug, fixed
