### ISSUE TITLE
Exclusion ranges overlap error when Clang is used as C++ compiler

### ISSUE THREAD

**Issue by davidbolvansky** [p4lang/p4c#3584] opened 2022-10-19 16:29 UTC
On Linux Ubuntu 20 LTS with clang 12 and newer and GC 7.6.4 or  8.2.2 (two version I tried) and simple "cmake ../" I always results in error "Exclusion ranges overlap" which is coming from Boehm GC.

**Comment by asl** [comment] 2022-10-19 19:02
@davidbolvansky on aarch64 linux (Ubuntu 20.04) with default clang 10 I'm getting hang of irgenerator when GC is enabled

**Comment by asl** [comment] 2022-10-19 19:03
(feel free to assign to me ;) )

**Comment by asl** [comment] 2022-10-19 19:47
The hang reason is similar to #3415. A bit more sophisticated workaround is necessary. I cannot reproduce "Exclusion ranges overlap" on aarch64/linux. Let's see if the new fix will fix your problem as well.

**Comment by asl** [comment] 2022-10-19 20:10
Now it seems we can reproduce the issue on CI: https://github.com/p4lang/p4c/actions/runs/3284630342/jobs/5410814947

**Closed** 2022-10-23 16:10 UTC
Labels: bug, fixed
