### ISSUE TITLE
EBPF PTF tests keep failing in CI

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#3946] opened 2023-03-28 00:26 UTC
See for example https://github.com/p4lang/p4c/actions/runs/4537501412/jobs/7995422114

**Comment by fruffy** [comment] 2023-03-28 00:43
I think this error is caused by the libbpf submodule update. 
https://github.com/p4lang/p4c/pull/3803/files

**Comment by mbudiu-vmw** [comment] 2023-03-28 00:46
any idea on how to undo this?

**Comment by fruffy** [comment] 2023-03-28 00:52
It's a little complicated once the submodule update has been committed but if you cd into the submodule folder, checkout commit [051a400](https://github.com/libbpf/libbpf/tree/051a4009f94d5633a8f734ca4235f0a78ee90469) and then commit that update, it should revert to the original state.

**Comment by mbudiu-vmw** [comment] 2023-03-28 01:19
However, each week-end I still get a message about ptf tests failing. That is unrelated.

**Closed** 2023-04-06 11:26 UTC
Labels: bug
