### ISSUE TITLE
Can p4c-dpdk also use `.p4-stderr` as file name suffix for stderr output in automated tests?

### ISSUE THREAD

**Issue by jfingerh** [p4lang/p4c#3610] opened 2022-10-24 17:03 UTC
It seems like all p4c back end automated CI tests use `.p4-stderr` as a file name suffix they write to, and have checked-in files in p4_16_samples_outputs, to compare actual p4c stderr output against expected p4c stderr output.

p4c-dpdk seems to use `.p4-error` instead.  Is there a good reason for this?  Perhaps because people wanted to use the same P4_16 source file as a test case for multiple back ends, and have different expected stderr output for p4c-dpdk back end vs. bmv2 or other back ends?

If there is no good reason to have a different suffix, it seems somewhat easier to keep track of if all back ends use the same suffix for this purpose.

**Comment by jfingerh** [comment] 2022-10-24 17:03
@usha1830 @hanw Do you know?

**Comment by mbudiu-vmw** [comment] 2022-10-24 17:10
The same program compiled with different backends will generate different errors.

**Comment by jafingerhut** [comment] 2022-10-24 18:20
I have since confirmed that there are about 173 pairs of files named foo.p4-stderr and foo.p4-error in the p4_16_samples_outputs directory, and while most such pairs are identical, several such pairs have different contents.  I believe during p4c automated test runs, this gives extra test coverage that p4c-dpdk produces expected error messages.

Closing this issue, as it appears everything is working as intended here.

**Closed by jafingerhut** 2022-10-24 18:20 UTC
