### ISSUE TITLE
v1model user-defined Metadata as subparser invocation parameter produces compiler bug  (bmv2 backend)

### ISSUE THREAD

**Issue by Xingdao-Fan** [p4lang/p4c#698] opened 2017-06-05 18:52 UTC
The following code yields a backend compiler bug (compiled with command `p4c-bm2-ss --p4v 16`). I narrowed it down to the presence of the user-defined Metadata being passed as an invocation parameter (regardless of `in`, `out`, or `inout` direction).

I've also tried passing a parameter of type `standard_metadata_t`, but no compiler bug occurs in this case.

```C++
parser Subparser(inout Meta m) {

 state start {
    transition accept;
 }

}

parser TopParser(packet_in b, out Parsed_packet p, inout Meta m,
   inout standard_metadata_t metadata) {

  Subparser() subparser;
	
  state start {
     subparser.apply(m);
     transition accept;
  }
}
```
> In file: ../backends/bmv2/expression.cpp:239
> Compiler Bug: ../backends/bmv2/expression.cpp:239: Null name

_________________________________________________
Complete P4 program:

```C++
#include <v1model.p4>

//------------------------------------------
header fixedLenHeader_h {
    bit<512> field;
}

//------------------------------------------
struct Meta {
    bit<8> metafield;
}

struct Parsed_packet {
    fixedLenHeader_h h;
}

//------------------------------------------
parser Subparser(inout Meta m) {

 state start {
    transition accept;
 }

}

parser TopParser(packet_in b, out Parsed_packet p, inout Meta m,
    inout standard_metadata_t metadata) {

  Subparser() subparser;

  state start {
    subparser.apply(m);
    transition accept;
  }
}

control VeryChecksum(in Parsed_packet hdr, inout Meta meta) {
  apply {  }
}

control IngressP(inout Parsed_packet hdr,
                      inout Meta meta,
                      inout standard_metadata_t standard_metadata) {
  apply {  }
}

control EgressP(inout Parsed_packet hdr,
                     inout Meta meta,
                     inout standard_metadata_t standard_metadata) { apply {} }

control ChecksumComputer(inout Parsed_packet hdr,
                              inout Meta meta) { apply {} }

control TopDeparser(packet_out b, in Parsed_packet hdr) { apply {} }

V1Switch(TopParser(), VeryChecksum(), IngressP(), EgressP(), ChecksumComputer(),
    TopDeparser()) main;
```

**Comment by mbudiu-vmw** [comment] 2017-06-05 20:18
Frankly I don't think this has anything to do with metadata; it seems to be caused by the usage of a local variable in a parser whose type is a struct. @hanw : this fails here:

```
auto name = ::get(backend->scalarMetadataFields, field);
CHECK_NULL(name);
```

**Comment by Xingdao-Fan** [comment] 2017-06-06 10:45
> Frankly I don't think this has anything to do with metadata; it seems to be caused by the usage of a local variable in a parser whose type is a struct. @hanw : this fails here:

I've tested with another struct (my bad for not doing that sooner). The code with this excerpt compiles just fine:

```C++
//------------------------------------------
struct Meta {
   bit<8> metafield;
}

struct Parsed_packet {
   fixedLenHeader_h h;
}

struct Teststruct {
   bit<8> data;
}
//-----------------------------------------------
parser Subparser(inout Teststruct m) {

 state start {
    transition accept;
 }

}

parser TopParser(packet_in b, out Parsed_packet p, inout Meta m,
    inout standard_metadata_t metadata) {

  Subparser() subparser;

  state start {
    Teststruct t;
    t.data = 0xDE; //deleting this line only produces a warning
    subparser.apply(t);
    transition accept;
  }
}
```

**Comment by mbudiu-vmw** [comment] 2017-06-06 17:03
@Xingdao-Fan : This is a very good bug report, my comment was just trying to narrow down the cause.
If you run the compiler with the -v flag you can see the list of all passes executed. Then you can choose a pass and dump the program as it looks at that point. I did the following: `./p4c-bm2-ss --top4 MidEnd_41 -v issue698.p4`. This dumps the program right after the mid-end; at this point inlining has happened, and the important part of the program looks like this:

```
parser TopParser(packet_in b, out Parsed_packet p, inout Meta m, inout standard_metadata_t metadata) {
    Meta m_1;
    state start {
        m_1.metafield = m.metafield;
        m.metafield = m_1.metafield;
        transition accept;
    }
}
```

This is what the back-end sees.

**Comment by Xingdao-Fan** [comment] 2017-06-08 15:36
@mbudiu-vmw I didn't know about this. Cool! Thanks for the tip =)

**Comment by mbudiu-vmw** [comment] 2017-09-01 03:51
This is a duplicate of issue #677.
This should be addresses by PR #879.

**Comment by mbudiu-vmw** [comment] 2017-10-17 15:57
I am assuming that we can close this issue.

**Closed by mbudiu-vmw** 2017-10-17 15:57 UTC
Labels: bug, duplicate, fixed
