### ISSUE TITLE
Investigate why casting bit<1> fields to bool breaks BMV2 STF tests

### ISSUE THREAD

**Issue by sethfowler** [p4lang/p4c#737] opened 2017-06-23 22:18 UTC
This issue was noticed [here](https://github.com/p4lang/p4c/pull/733#discussion_r123853884). I haven't investigated further. To reproduce it, it's sufficient to edit `synthesizeValidField.cpp` and in `RewriteIsValidCalls::postorder(IR::MethodCallExpression* expr)`, replace these lines:

```c++
    auto constant = new IR::Constant(IR::Type::Bits::get(1), 1);
    return new IR::Equ(expr->srcInfo, member, constant);
```

With this line:

```c++
    return new IR::Cast(expr->srcInfo, IR::Type::Boolean::get(), member);
```

A log file of the resulting test failures: [test-suite.log.txt](https://github.com/p4lang/p4c/files/1099171/test-suite.log.txt)

**Comment by Xingdao-Fan** [comment] 2017-06-29 10:59
Not sure if related, but the simple switch itself seems to be misbehaving when the bool type is involved.

See [here](https://github.com/p4lang/behavioral-model/issues/399).

**Comment by sethfowler** [comment] 2017-06-29 21:10
p4lang/behavioral-model#399 was closed; this problem is believed to be the compiler's fault. (We're not generating a necessary cast.)

**Comment by sethfowler** [comment] 2017-06-29 21:11
I'm sure this is the same problem, though. Thanks for providing a test case that demonstrates it!

**Comment by hanw** [comment] 2017-06-29 21:15
Although #751 only fixed the cast from bool -> bit<1>, not the other way around.

**Comment by mbudiu-vmw** [comment] 2017-11-08 05:25
@sethfowler : do we have a test case that fails?
This issue is very vague. Unless we can get a test case I am tempted to close it.

**Comment by jafingerhut** [comment] 2017-11-08 20:21
In general, I believe all `bit<W>` and `bool` _operations_ in the bmv2 JSON operate on different 'stacks' of values, e.g. "and" and "or" operators pop two values from a boolean data stack, and push a value back on the boolean data stack, but bitwise "&" and "|" pops two values from a bitvector data stack, and pushes a value back on the bitvector data stack.

bmv2 does _no_ error checking on the expressions it reads in the JSON file to ensure that the operands of an operator have the expected type (AFAIK).

p4c generating JSON with incorrect combinations of operator/operand types was the root cause for this issue: https://github.com/p4lang/p4c/issues/950

I wouldn't be surprised if it was the root cause for other issues involving expressions with boolean types.

It probably wouldn't be terribly difficult to write a checker for bmv2 JSON expressions to statically check for wrong nesting of operators.

**Comment by mbudiu-vmw** [comment] 2017-11-08 20:50
The logical place for that checker is BMv2 itself.

**Comment by jafingerhut** [comment] 2017-11-08 20:55
or in p4c-bm2-ss bmv2 backend code, after generating the JSON data, but before writing it :-)

**Comment by jafingerhut** [comment] 2017-11-09 02:54
[bmv2-json-check.py.txt](https://github.com/p4lang/p4c/files/1456143/bmv2-json-check.py.txt)

As an experiment, I hacked up a Python program to walk through expressions in parser "set" operations, conditional nodes, and "assign" statements in the match-action pipeline in a JSON file, and calculate the type of each subexpression (I used bit-vector, bool, header, header_union as the 'types', which are all there are as far as bmv2 is concerned, I think), and check whether each operator was given operands of the correct type.

It found no problems with any program in testdata/p4_16_samples/*.p4 in the latest master version, when compiling with the most recent p4c-bm2-ss that has the fix for issue #950.

It found problems with two JSON files created using p4c-bm2-ss from the commit just before the fix for issue #950.  One was flag_lost-bmv2.p4, the test program added with the fix for issue #950.  The other was issue737-bmv2.p4, the test program for this issue.  There were 96 other JSON files with no problems found by my little Python program, before and after the fix for issue #950.

That isn't a proof that there are no more such issues to be found in the P4 compiler, of course -- just that those set of test programs do not cause such erroneous JSON files to be generated.

I have attached the Python program I used for reference, in case it is of use to anyone.  Agreed that having such checks in bmv2 would be a logical place for them.  They would only be there for the purpose of catching bugs in the compiler, but such bugs are pretty subtle to notice and not easy to debug.

**Comment by jafingerhut** [comment] 2017-11-09 03:00
[issue399.p4.txt](https://github.com/p4lang/p4c/files/1456152/issue399.p4.txt)

The attached program issue399.p4 is a 1-line update of a complete program from a comment on issue #399 (just so it compiles with the latest v1model.p4 with the recent direction in -> inout for verifyChecksum control).

When compiled with p4c-bm2-ss from before the fix for issue #950, my little Python program detects a 'type error' in the generated JSON file, which will likely lead to silent misbehavior if simple_switch is used to run the program, like the other programs mentioned above.

When compiled with the most recent p4c-bm-22, after the fix for issue #950, my little Python program detects no such 'type errors' in the generated JSON file.  Likely correct.

**Comment by jafingerhut** [comment] 2017-11-09 03:17
Last comment from me on this unless I actually have something better to say (and hopefully I'm not dumping analysis of an issue #950 that it turns out is actually unrelated to this issue).

Pointer to bmv2 code showing it has multiple different 'data stacks' for operands, and is basically just assuming that operations are nested properly, otherwise it is grabbing operands for operators that are results of some wrong sub-expression, or perhaps even undefined garbage data.

The multiple data stacks (bool is only for bool values, data is for any bit-vector value, header for headers, etc.): https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/expressions.cpp#L331-L349

Code for bitwise AND (&) primitive that pops from data stack, and pushes back to data stack: https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/expressions.cpp#L560-L565

Code for logical NOT (!) primitive that pops from bool stack, and pushes back to bool stack: https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/expressions.cpp#L560-L565

Code for D2B that pops from data stack, pushes result to bool stack: https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/expressions.cpp#L614-L617

**Comment by mbudiu-vmw** [comment] 2017-11-09 18:27
@jafingerhut : if you think this is worthwhile maybe you want to integrate your type-checking script into the bmv2 backend testing script, which is also python.

The right place to integrate it would probably be in the run-bmv2-test.py script, in the process_file method, right after run_timeout (which runs the compiler).

**Closed** 2017-11-17 20:26 UTC
Labels: bug, fixed
