### ISSUE TITLE
p4c can't compile direct meter

### ISSUE THREAD

**Issue by JackSunshine** [p4lang/p4c#1167] opened 2018-02-23 00:25 UTC
Hi
I'm from ONOS community,  I'm testing meter feature on Bmv2, the compiler always complains this error:
sdn@onos-p4-dev:~/onos/pipelines/basic/src/main/resources$ make basic
p4c-bm2-ss -o p4c-out/bmv2/basic.json \
    --p4runtime-file p4c-out/bmv2/basic.p4info \
    --p4runtime-format text basic.p4
In file: /home/sdn/p4tools/p4c/backends/bmv2/metermap.cpp:41
Compiler Bug: /home/sdn/p4tools/p4c/backends/bmv2/metermap.cpp:41: Null info

Makefile:4: recipe for target 'basic' failed
make: *** [basic] Error 1

here is the table0.p4

#ifndef __TABLE0__
#define __TABLE0__

#include "headers.p4"
#include "defines.p4"

control table0_control(inout headers_t hdr,
                       inout local_metadata_t local_metadata,
                       inout standard_metadata_t standard_metadata) {

    direct_counter(CounterType.packets_and_bytes) table0_counter;
    direct_meter<MeterColor_t>(MeterType.bytes) table0_meter;

    action set_next_hop_id(next_hop_id_t next_hop_id) {
        local_metadata.next_hop_id = next_hop_id;
    }

    table table0 {
        key = {
            standard_metadata.ingress_port : ternary;
            hdr.ethernet.src_addr          : ternary;
            hdr.ethernet.dst_addr          : ternary;
            hdr.ethernet.ether_type        : ternary;
            hdr.ipv4.src_addr              : ternary;
            hdr.ipv4.dst_addr              : ternary;
            hdr.ipv4.protocol              : ternary;
            local_metadata.l4_src_port     : ternary;
            local_metadata.l4_dst_port     : ternary;
        }
        actions = {
            set_egress_port(standard_metadata);
            send_to_cpu(standard_metadata);
            set_next_hop_id();
            _drop();
        }
        const default_action = _drop();
        counters = table0_counter;
        meters = table0_meter;
    }

    apply {
        table0.apply();
     }
}

#endif

Thanks

**Comment by jafingerhut** [comment] 2018-02-23 04:03
There is a test program linked below that is part of the p4c set of test programs, and it uses direct meters, and gives no compilation errors with the latest version of p4c.

Do you know what version of p4c source code you are using?  If you can try using the latest version built from p4c source code, and still get the error, then please attach a complete copy of the source code you used (e.g. your example above has #include directives for files that you do not include).

**Comment by JackSunshine** [comment] 2018-02-23 06:18
I'm using 
sdn@onos-p4-dev:~$ p4c --version
p4c 0.1
sdn@onos-p4-dev:~$ p4c-bm2-ss --version
p4c-bm2-ss
Version 0.0.5
what's the latest version of the p4c compiler?

you can find other the other p4 codes from here:
https://gerrit.onosproject.org/#/c/15564/
https://github.com/opennetworkinglab/onos/tree/master/pipelines/basic/src/main/resources

table0.p4 with a direct meter just as above.

**Comment by JackSunshine** [comment] 2018-02-23 06:57
Seems I found the problem, direct meter need to implement the action in actions. Thanks

**Comment by JackSunshine** [comment] 2018-02-23 07:10
Hi @jafingerhut , Is there any test programs about meter(not direct meter)? many thanks!

**Comment by hesingh** [comment] 2018-02-23 16:50
@JackSunshine , see

https://github.com/p4lang/p4c/blob/master/testdata/p4_14_samples/meter.p4

**Comment by jafingerhut** [comment] 2018-02-24 00:02
The version number printed by "p4c --version" does not change very often, I think, even though bug fixes are committed to the Github repository https://github.com/p4lang/p4c.  The commit and/or date of the last commit of the source code version you have is thus more precise in identifying a version than the 'p4c --version' number.

The first output you showed contained the line "Compiler Bug: /home/sdn/p4tools/p4c/backends/bmv2/metermap.cpp:41: Null info".  That suggests that perhaps there is an internal bug in the p4c compiler that you triggered with your P4 program.  If you have a complete set of source files that triggers a similar error in the latest version of p4c, attaching those to an issue would be interesting to the p4c developers.

The example that @hesingh pointed you at is P4_14 source code, whereas your program is the later P4_16 version of the language.  I do not see an already-checked-in test case for P4_16 source with an "indexed" meter (i.e. not direct, but indexed via an integer index).

**Comment by JackSunshine** [comment] 2018-02-24 07:37
I think if you create a direct meter in a table without corresponding action will trigger this error,  please refer to table0.p4 I posted the first time.

the following program is that I have modified by referring to [1], it can be compiled successfully
[1] https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/named_meter_1-bmv2.p4

#ifndef __TABLE0__
#define __TABLE0__

#include "headers.p4"
#include "defines.p4"

control table0_control(inout headers_t hdr,
                       inout local_metadata_t local_metadata,
                       inout standard_metadata_t standard_metadata) {

    direct_counter(CounterType.packets_and_bytes) table0_counter;
    direct_meter<bit<32>>(MeterType.bytes) table0_meter;

    action set_next_hop_id(next_hop_id_t next_hop_id) {
        local_metadata.next_hop_id = next_hop_id;
    }
    
    action read_meter(bit<9> meter_idx) {
        standard_metadata.egress_spec = meter_idx;
        table0_meter.read(local_metadata.meter_tag);
    }
    
    table table0 {
        key = {
            standard_metadata.ingress_port : ternary;
            hdr.ethernet.src_addr          : ternary;
            hdr.ethernet.dst_addr          : ternary;
            hdr.ethernet.ether_type        : ternary;
            hdr.ipv4.src_addr              : ternary;
            hdr.ipv4.dst_addr              : ternary;
            hdr.ipv4.protocol              : ternary;
            local_metadata.l4_src_port     : ternary;
            local_metadata.l4_dst_port     : ternary;
        }
        actions = {
            set_egress_port(standard_metadata);
            send_to_cpu(standard_metadata);
            set_next_hop_id();
            read_meter();
            _drop();
        }
        const default_action = _drop();
        counters = table0_counter;
        meters = table0_meter;
    }
    
    table filter {
        actions = {
            _drop;
            NoAction;
        }
        key = {
            local_metadata.meter_tag: exact;
        }
        size = 16;
        default_action = NoAction();
    }
    apply {
        table0.apply();
        filter.apply();
     }
}

#endif

**Comment by jafingerhut** [comment] 2018-02-24 08:59
It would be helpful if you could also attach or give a link _directly to the single files_ headers.p4 and defines.p4 that are included by that sample program.  I can't really try reproducing it without those.  I looked at the links you gave before, but it is not easy to see which files you mean, since they link to a page mentioning many files.

**Comment by JackSunshine** [comment] 2018-02-27 03:35
Sorry for inconvenience, here is the whole program, please go to root directory, run make basic
[resources.zip](https://github.com/p4lang/p4c/files/1761129/resources.zip)

**Comment by jafingerhut** [comment] 2018-02-28 13:11
Attached is a smaller P4_16 program issue1167.p4, using v1model.p4, that causes the latest version of p4c as of 2018-Feb-16 to give the following error message when compiling:
```
In file: /home/jafinger/p4c/backends/bmv2/metermap.cpp:41
Compiler Bug: /home/jafinger/p4c/backends/bmv2/metermap.cpp:41: Null info
```
It has a comment in action 'foo' showing a line of code that, when uncommented, causes the error message to go away, although I am not sure if the BMv2 JSON file produced is actually correct, since the BMv2 JSON definition of the action 'foo' then has no method call for the direct_meter instance 'my_meter'.

I am not sure how important this issue might be considered by the p4c developers, given that hopefully implementation of PSA will begin soon, and this bug might be specific to the v1model.p4 architecture's way of implementing direct_meter's.
[issue1167.p4.txt](https://github.com/p4lang/p4c/files/1767146/issue1167.p4.txt)

**Comment by mbudiu-vmw** [comment] 2018-02-28 17:21
This seems to happen because the code to generate json for tables is executed before the code that processes the meter declarations. I find it strange that we never had a test for this case.

**Comment by mbudiu-vmw** [comment] 2018-02-28 18:05
@hanw: I have assigned this to you. My simple attempt to fix it failed; the order in which data structures are populated seems quite complicated: the meter map is populated as a result of compiling actions - so corresponding entries do not exist if the meter is never invoked.

There seem to be two different bugs in this issue: one is that if you never invoke the meter the compiler fails, and the second is that if you invoke the meter there is no json code generated for it.

**Comment by hanw** [comment] 2018-02-28 18:07
Sure, I will take a stab at it.

**Comment by mbudiu-vmw** [comment] 2019-04-19 17:18
From my testing it looks like this issue has been resolved; the program of @jafingerhut will actually report a clear error to the user. So I will mark this as fixed, and hopefully close it if no one objects.

**Comment by jafingerhut** [comment] 2019-04-20 06:10
Agreed that this issue should be fixed now, in that programs with this kind of mistake will give a relatively clear error message, and no longer a "Compiler Bug" message.

**Closed** 2019-04-21 02:39 UTC
Labels: bug, fixed
