### ISSUE TITLE
Implicit casts in function calls

### ISSUE THREAD

**Issue by hackedy** [p4lang/p4c#2334] opened 2020-04-23 00:51 UTC
The spec [says that](https://p4.org/p4-spec/docs/P4-16-v1.2.0.html#sec-invocations) "[the] compiler does not insert implicit casts for the arguments to methods or functions—the argument types must match the parameter types exactly," but p4c is more permissive, e.g., the following program typechecks.
```
int<8> f(int<8> input) {
  return input;
}

control C() {
  apply {
    int<8> z = f(1);
  }
}
```

**Comment by hackedy** [comment] 2020-04-23 00:56
I've filed an issue at the spec that covers this and other implicit cast weirdness: p4lang/p4-spec#842

**Comment by hackedy** [comment] 2020-04-23 14:09
p4-spec#843 changes the spec to allow implicit casts for `in` arguments. I tried a few more examples and got a "Null cst" bug message from the following program.
```
int<8> f(in int<8> input, out int<8> output) {
  output = input;
}

control C() {
  apply {
    int x = 0;
    int<8> z = f(1, x);
    int<8> y = x+8w1;
  }
}
```

Error message:
```
In file: /home/ryan/dev/p4c/frontends/p4/typeChecking/typeChecker.cpp:2009
Compiler Bug: /home/ryan/dev/p4c/frontends/p4/typeChecking/typeChecker.cpp:2009: Null cst

```

**Comment by hesingh** [comment] 2020-04-23 14:31
I tweaked the program to fix the error.

```
int<8> f(in int<8> input, out int<8> output) {
  output = input;
}

control C() {
  apply {
    int<8> x = 0;
    int<8> z = f(1, x);
    int<8> y = x+8s1;
  }
}
```

p4c does not implicitly cast the out parameter,

**Comment by jafingerhut** [comment] 2020-04-23 14:34
@hesingh That is good to note, but the p4c developers tend to want to fix at least most situations where the compiler actually crashes, so the example program that causes it to do so is still an interesting test case.

**Comment by hesingh** [comment] 2020-04-23 14:45
I think we could change this line of p4c code:

https://github.com/p4lang/p4c/blob/master/frontends/p4/typeChecking/typeChecker.cpp#L2009

to an error message because the issue is not a compiler bug.

**Comment by hackedy** [comment] 2020-04-23 14:46
Ah, the f() call is unrelated to the crash. I mean, it's doing a cast or something to make x match the parameter type bit<8>, which may be a problem? But I'm getting the same crash from the program without `f`.
```
control C() {
  apply {
    int x = 0;
    int<8> y = x + 8w1;
  }
}
```

**Comment by hesingh** [comment] 2020-04-23 16:00
From section 8.9.2, of the working spec, I see this binary op in  `x + 8w1;` should be allowed by p4c by implicitly casting `x` to  int<8>.

"In particular, applying a binary operation to an expression of type int and an expression with a fixed-width type will implicitly cast the int expression to the type of the other expression."

I see if `x` is declared as `int<8> x;` then `x + 1` is changed by p4c as follows with an implicit cast.

`x + (int<8>)1`.

If I my analysis is correct, p4c needs a fix to the latest example that @hackedy posted - thanks.

**Comment by hackedy** [comment] 2020-04-23 16:36
OK, another example. Bit types bit<w> support the concatenation operator ++, but signed types do not. But p4c accepts this program.
```
void f() {
  int<16> x = 8s8 ++ 8s8;
}
```
Maybe this one is a spec issue, since the spec explicitly says int<> types are laid out in two's complement, so the ++ operation is unambiguous.

**Comment by jafingerhut** [comment] 2020-04-23 16:39
@hesingh I am pretty sure that this program:
```
control C() {
  apply {
    int x = 0;
    int<8> y = x + 8w1;
  }
}
```
is not legal according to the P4_16 language spec, because type `int` is only allowed for compile-time known values, not for run-time variables.  Perhaps there is a p4c bug that there is no compile-time error for that declaration of `x`?

**Comment by hesingh** [comment] 2020-04-23 16:43
@jafingerhut Ah, thanks.  Even I noticed that p4c allows implicit cast with a binary op if the `int` variable is a compile-time constant.  I got fooled because `x` is assigned to a compile time constant by `int x = 0;`  before being used in a binary op and should be allowed.

**Comment by jafingerhut** [comment] 2020-04-23 16:46
Regarding the `++` operator on values of type `int<W>`, I think it may have intentionally been left out of the operations supported on type `int<W>`.

I agree that it would be perfectly reasonable to define its behavior on values of type `int<W>`, if people wanted to do so, but there might not be much interest in doing so, either.

**Comment by mbudiu-vmw** [comment] 2020-04-23 17:12
There are many issues here, it would be easier if you filed one per bug.
Otherwise we don't know when you're done extending this one.

**Comment by mbudiu-vmw** [comment] 2020-04-23 17:12
some of these are bugs

**Comment by jafingerhut** [comment] 2020-04-23 17:19
I have created one separate issue here: https://github.com/p4lang/p4c/issues/2335

From what I can tell so far, there are no others that need to be created from comments before this one, but feel free to create additional issues if I have missed any.

**Comment by mbudiu-vmw** [comment] 2020-05-05 19:55
I will mark this as fixed; with the new PR filed against the spec I think all problems described here are addressed. https://github.com/p4lang/p4-spec/pull/853

**Closed** 2020-05-28 23:33 UTC
Labels: bug, fixed
