### ISSUE TITLE
3% Tests passed only

### ISSUE THREAD

**Issue by razimattar** [p4lang/p4c#1268] opened 2018-05-03 19:47 UTC
Hello,

I installed all dependencies as noted in the Read Me file on Ubuntu 16.04, and installed it.
After I tried this step
make -j4 check 
I get "3% tests passed, 970 tests failed out of 998" see picture:
![failed_tests](https://user-images.githubusercontent.com/38960626/39598963-f19e9006-4f22-11e8-8878-b89348cb68c2.png)

Tried again and got:
![p4_not_working](https://user-images.githubusercontent.com/38960626/39599069-41b98ee2-4f23-11e8-9d8c-5de45d6482d2.png)

I tried to run one of the exercises provided in the tutorial, and got this error:
![p4c_run_error](https://user-images.githubusercontent.com/38960626/39599230-d592c930-4f23-11e8-9225-74d77dcb0fb8.png)

Any idea what could be the cause of this? 

Thanks

**Comment by hesingh** [comment] 2018-05-03 21:55
To compile bmv2, you need to use p4c-bm2-ss.

Did you git clone p4c using --recursive option?

**Comment by jafingerhut** [comment] 2018-05-03 22:05
I do not recognize what is wrong from the symptoms you have, but I can tell you that I have successfully installed p4lang/behavioral-model (including the few packages it needs installed by running its included install_deps.sh script), Google Protocol Buffers 0.3.2, and p4lang/p4c many times on many Ubuntu 16.04 Linux machines using the steps in this bash script, usually by running the script rather than copying and pasting the lines one at a time, but either way should work for you on a freshly installed Ubuntu 16.04 Linux machine, too (with at least 2 Gbytes of RAM and 11+ Gbytes of disk space): https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev.sh

**Comment by hesingh** [comment] 2018-05-03 22:13
We should also use the p4-dev mailing list instead of filing an issue such as this.

**Comment by mbudiu-vmw** [comment] 2018-05-03 22:25
None of your screenshots shows why a test has failed. Look at the error messages produced by a failing test.

**Comment by mbudiu-vmw** [comment] 2018-05-09 15:46
I will close this issue, since it is not complete enough to diagnose what the problem is.

**Closed by mbudiu-vmw** 2018-05-09 15:46 UTC
Labels: question
