### ISSUE TITLE
make -j4 check fail,at 895 case

### ISSUE THREAD

**Issue by Yukinarii** [p4lang/p4c#1033] opened 2017-11-13 17:44 UTC
![image](https://user-images.githubusercontent.com/20517836/32740137-ea72cd3c-c8dc-11e7-9739-0b6a8c6acbbe.png)

**Comment by mbudiu-vmw** [comment] 2017-11-13 17:47
This is a duplicate of #924; we already have a PR for this bug, but it has not yet been approved.

**Comment by Yukinarii** [comment] 2017-11-13 18:01
Thanks for response.May I know the time that when the PR will be approved?

**Comment by mbudiu-vmw** [comment] 2017-11-13 19:06
As soon as someone with commit access will review it and accept it.
There's a little backlog of PRs unreviewed.
These guys must be busy.

**Comment by mbudiu-vmw** [comment] 2017-11-13 20:58
It looks like the patch was actually merged a while back. Are you running a recent build of the compiler?
Maybe you can just run ./test/gtestp4c and see the detailed error message shown.
The fix only handled a failure in a test called P4_14_MatchFields.

**Comment by Yukinarii** [comment] 2017-11-14 18:45
Hello,I find gtestp4c.cpp does not be compiled. 
I guess it's because I didn't give "-DCMAKE_BUILD_TYPE=RELEASE|DEBUG" when I use cmake, but while I use the command "cmake .. -DCMAKE_BUILD_TYPE=RELEASE|DEBUG", I get an error message such like "DEBUG : command not found".

**Comment by Yukinarii** [comment] 2017-11-14 18:46
I have tried to rebuild,and only give "-DCMAKE_INSTALL_PREFIX=<path>", and it success to pass the test.Thank you!

**Comment by mbudiu-vmw** [comment] 2017-11-14 18:50
You should give either RELEASE or DEBUG, but not both.
The vertical bar in this context means "or".

**Comment by Yukinarii** [comment] 2017-11-14 18:56
Got it.Thanks!

**Closed** 2017-11-14 20:31 UTC
Labels: duplicate
