### ISSUE TITLE
frontends/p4/simplifyDefUse.cpp  FindUninitialized::readLocations not behaving as expected.

### ISSUE THREAD

**Issue by boblytton** [p4lang/p4c#2654] opened 2021-01-21 19:10 UTC
Hi
I am trying to understand the intention of using a pointer **const IR::Expression*** as a key for the map, and also using **readLocations.emplace()** to insert.
If you have expressions that are equivalent (same value) but not equal (different object), both can be emplaced - this seems to be the expected behaviour.
However, if the same expression object is used in multiple statements, only the first expression will be empaced.

Here is the code that I am interested in:
```
control ingress() {
    bit<8> temp;
    action m_action(bit<14> meter_idx) {
        temp = my_meter.execute(meter_idx);   //  address of 'temp' expression same as
        meter_tag[31:8] = 24w0;
        meter_tag[7:0] = temp;                //  the address of this 'temp' expression.
    }
    ...
```
When **FindUninitialized** passes over the code, the first **temp** expression is inserts with **LocationSet::empty**.
The second **temp** expression fails to add **'loc_temp'** as **readLocations** already holds a **temp**.
Thus the first **temp** is removed viz:
```
control ingress() {
    bit<8> temp;
    action m_action(bit<14> meter_idx) {
        my_meter.execute(meter_idx);   //  'temp' removed.
        meter_tag[31:8] = 24w0;
        meter_tag[7:0] = temp;
    }
    ...
```
(I am hoping that @mbudiu-vmw may be able to help?)

**Comment by mbudiu-vmw** [comment] 2021-01-21 19:43
Do you have a full example that reproduces this error?

This is a feature of the IR that has caused many relatively hard to diagnose bugs in the compiler.

In general you cannot know when syntactically identical expressions are represented by the same node in the IR or when they are distinct nodes. Some passes will "tree-ify" (parts of) the IR representation, converting DAGs where expressions are shared into trees where expressions are cloned. It looks like we are missing a pre-processing step to ensure that this happens in this case. Indeed, you can only use pointers to IR nodes when they are supposed to be distinct. 

I haven't figured out yet a general rule on how to do this safely in all contexts. As a developer I also frequently forget that this can happen.

Note that this feature can actually be useful, e.g., as a form a value-numbering used for common-subexpression elimination, but after this many bugs I think that we would be better without it.

**Comment by boblytton** [comment] 2021-01-21 20:57
I do not have an example that runs on the p4lang/p4c.

I have a unit-test that
    runs the front-end
    followed by a pass that `RewriteConcatToSlices` , adding the temporary as seen above.
    and then DoLocalCopyPropagation & DoSimplifyDefUse.

I guess to demonstrate a pass that replaced equivalent expressions with pointer to the same expression object would need to be written.

**Comment by mbudiu-vmw** [comment] 2021-01-21 21:26
You can also create a PR that modifies the compiler and fails, including your additional pass.

Often it's enough to invoke the Tranform called ClonePathExpressions; this will convert shared PathExpressions into distinct DAG nodes. It looks like it will be enough to handle the case you described. The question we should resolve is whether we have to include a call to the ClonePathExpressions always before we do the DefUse-based optimizations.

**Comment by boblytton** [comment] 2021-01-26 16:11
Hi @mbudiu-vmw,

Running ClonePathExpressions is a good solution, along with rerunning TypeChecking - thank you!

Whilst running DoSimplifyDefUse I am hitting `BUG_CHECK(false, "Overwriting definitions");` in `setDefinitionsAt()`.
I am working on extracting a reduced test case (the few failing P4 programs are large) and wondered if you could think of a reason why `ProgramPoint` could be the same?

**Comment by mbudiu-vmw** [comment] 2021-01-26 17:30
It's difficult to guess. ProgramPoint is supposed to represent a context-sensitive analysis, and it maintains a call stack. But for some operations, like parameter assignment from arguments, the representation of the context may be imprecise. So perhaps there are two contexts that create the same ProgramPoint?

**Comment by boblytton** [comment] 2021-01-26 17:35
thank you

**Comment by mbudiu-vmw** [comment] 2021-04-20 23:25
There isn't enough information to reproduce this problem.

**Comment by mbudiu-vmw** [comment] 2021-05-28 23:44
I will close this issue, if you think it should be left open please reopen and supply a failing test case.

**Closed by mbudiu-vmw** 2021-05-28 23:44 UTC
Labels: bug
