### ISSUE TITLE
Reference tables from another control block

### ISSUE THREAD

**Issue by jphurl** [p4lang/p4c#2629] opened 2020-12-08 21:54 UTC
We want to model table dependencies (using annotations), and we want to directly reference the path expression, like so:
```p4
control c() {
    table t { ... }
    @depend(t) table t2 { ... }
...
}
```
but the issue is that some table may depend on another which is not in the same control block:
```p4
control c1() {
    table t { ... }
...
}
control c2() {
    @depend(c1.t) table t2 { ... }  // c1.t does not compile
...
}
```
Is this possible? If not, is this a feasible request?

Currently we have to use the table name as a string, which we would like to avoid if possible.

**Comment by mbudiu-vmw** [comment] 2020-12-08 21:58
The problem is that c1 is more like a class than an object: you have to instantiate c1 to get an object.
So there isn't really a thing named `c1.t`: for every instance of c1 that will create you will get another `t`.
```
control c1()  {
     c1() c1_0, c1_1;  // each of these has a `t` inside. 
}
```

**Comment by jphurl** [comment] 2020-12-08 22:03
but even `c1_0.t` will not work:
```
error: Cannot extract field t from c1_0 which has type control c1
```
Is this a feasible request?

**Comment by mbudiu-vmw** [comment] 2020-12-08 22:08
Unfortunately the language spec dictates that declarations within a parser are control are private:
https://p4.org/p4-spec/docs/P4-16-v1.2.1.html#sec-name-visibility

This is a possible feature that could be added to the language - visibility modifiers (e.g., public) if there is a use case for them, but no one has proposed this yet.

Even assuming that you do make the declarations visible, you will be faced with the problem that the compiler will inline the controls and rename variables; the compiler has to understand your annotations to preserve the names when doing that.

**Comment by jphurl** [comment] 2020-12-08 22:23
Thank you @mbudiu-vmw, it seems there is not really an elegant solution here. We pretty much always only instantiate control blocks once, so maybe if we could mark a control block as 'static' so to speak (only one instance) - we could pair this with the `public` modifier to get what we want and hopefully avoid the inlining somehow... just thinking out loud.. Feel free to do with this ticket what you want :) and thanks again

**Comment by mbudiu-vmw** [comment] 2020-12-08 22:31
I can see several possibilities:
- hack the compiler adding the capabilities you need (singleton pattern, visibility modifiers, renaming passes that consistently change names, etc). If you do that you can contribute your changes back to the community and see whether other people could benefit from them, and get them potentially integrated in the compiler. After all, this is one of the benefits of the code being available.
- use string annotations, as you are already doing. The problem with renaming still remains, but perhaps the `@name` annotations that the compiler inserts are enough for you to recover the original names
- use a higher level language and tool that generates P4 and feeds it to the standard compiler after you analyze the program and extract the information you need. You could perhaps build this on top of the existing codebase by adapting the existing parser.

The best solution will depend on what kind of information you really need to extract from your program. Writing a compiler analysis to build the control/and data dependence graph between the tables is not particularly difficult, but I assume you have a different notion of dependency in mind and you want to feed to the tools information that is not apparent in the source program.

**Comment by hesingh** [comment] 2020-12-09 00:16
Let's not use Annotation.  Add a new tag in `public` to `table t`.  Use `depends` with `table t2`. Whenever compiler changes any names, the compiler should change all instances of `t`.  Thereafter, use static control or instantiate control to get `table t`.

```C
control c1() {
    table t public { ... }
...
}
control c2() {
   table t2 depends t { ... } 
...
}
```

**Comment by hesingh** [comment] 2020-12-09 00:42
What I am saying is extend p4lang with appropriate new keywords and make sure the table names are recoverable by p4c internal code after compiler passes have renamed objects.  One can always store the public table name and its control in an internal store in p4c to find and use anywhere else in p4c internal code.

**Comment by stefanheule** [comment] 2020-12-09 00:53
For what it's worth, we at Google have actually been using annotations to track dependencies between tables too. Let me show you what we have done, and you might find something useful. It's definitely slightly different, but maybe some of the ideas transfer.

So first of all, we don't have tables that depend on other tables, instead we track dependencies between individual table entries. Imagine you have a table A where entries have some sort of ID, and another table B that has a match field or action paramter that refers to that ID. This creates a dependency between these entries, and e.g. you need to insert entries in A for some ID x before you can refer to that ID x from B. Similarly, deleting must go the other way around. I'm not sure if that's similar to your dependencies or not, but we have the same problem where we want to refer to table B from A (or even more, refer to a match field of table A from B).

So how do we track these? Using an annotation `@refers_to`. Let me show an example:

```
  table A {
      key = {
          some.id : exact @name("id");
      }
      actions = {
        //...
        @defaultonly NoAction();
      }
      const default_action = NoAction();
  }

  action some_action(@refers_to(A, id) bit<...> some_arg_name) {}
  
  table B {
      key = {
          // ...
      }
      actions = {
        some_action;
        @defaultonly NoAction();
      }
      const default_action = NoAction();
  }
```

So, in terms of naming, we just use the table name and assume it's unique. Just like you, that's fine for our usecases, we don't instantiate blocks multiple times for the moment. For the match fields, we use the `@name` annotation.

Obviously by itself this annotation won't do anything, but we built some tools around this for our use-cases (e.g. automatically "sequencing/batching" P4RT requests so that dependent table entries go into separate batch Write requests.

Hope this helps :)

**Comment by mbudiu-vmw** [comment] 2020-12-09 00:55
This trick will work if all tables are in the same control, but they have an additional problem that tables are in different controls.

**Comment by stefanheule** [comment] 2020-12-09 00:56
Our tables are in different controls, why is that a problem (but fair, my example is not complete enough to show that).

**Comment by mbudiu-vmw** [comment] 2020-12-09 00:57
How do you name a table in a different control without the compiler complaining?

**Comment by stefanheule** [comment] 2020-12-09 00:58
The compiler does not parse/interpret anything within an annotation (unless it's a standard annotation, which `@refers_to` and `@depends` are not).

**Comment by mbudiu-vmw** [comment] 2020-12-09 00:59
I was pretty sure that the way you wrote it the compiler will actually try to resolve A and id as expressions.

**Comment by stefanheule** [comment] 2020-12-09 01:09
That's not how annotations work as far as I understand. The only requirement is that the thing between `(` and `)` tokenizes, and has matching parens, but no other constraints are placed on the contents of the annotation.

We are definitely using the `@refers_to` annotation in our code, so empirically it's also working :)

**Comment by mbudiu-vmw** [comment] 2020-12-09 01:17
I see, initially the grammar for annotations required an expressions, but with the introduction of free-form annotations we no longer require that. Indeed, the standard annotations that require expressions will then try to resolve the identifiers that show up in the expressions in their context. I wonder why their `@depend` annotation does not compile, then. 

I have tried this program:
```
#include <core.p4>

control c1() {
    table t { keys = {}; actions = {} }
    apply { }
}

control c2() {
    @depend(c1.t) table t2 { keys = {}; actions = {} }
    apply { }
}

control c();
package top(c _c1, c _c2);
top(c1(), c2()) main;
```
and the compiler does not complain. Of course, it also does not really understand what `c1.t` is.
What is the error you see when you try to use this?

**Comment by vgurevich** [comment] 2020-12-09 04:30
I want to add that @jnfoster , @jafingerhut  and myself had a discussion on a similar subject, specifically how to give each and every named P4 object a global , unambiguous name. Pragmas/annotations are an important use case, but so are various debugging and analysis tools that have to work with the program as a whole (which is somewhat specific to P4). 

Unfortunately, we've also found out that the rules, currently employed in P4 are not sufficient for a couple of reasons:
1. One of the biggest problems are packages that have parameter names that work differently compared to parameters of parsers or controls -- the former cannot be changed by the programmer and the latter can
2. There are scopes that do not have names (i.e. unnamed blocks), inside which instantiations are still allowed
3. Instantiations can also happen inside expressions, which also are not named
4. Often expressions need to be named, e.g. expressions used as table keys or specific instantiations of actions with directional parameters -- there are a couple of issues on that subject in p4-spec. 

I do not have good solutions so far, but am quite open to ideas/suggestions/collaboration proposals (but we should probably move to p4-spec).

**Comment by jphurl** [comment] 2020-12-09 10:24
> What is the error you see when you try to use this?

@mbudiu-vmw 
I have a `PARSE_EXPRESSION_LIST("depend")` call, which then leads to the error I mentioned above. 

Say we leave this `PARSE` call out - If the compiler doesn't know what this `c1.t` is, then I am guessing it is not possible to get an `IR::PathExpression` out of it to find the `t` table decl descriptor, right?

**Comment by mbudiu-vmw** [comment] 2020-12-09 18:57
@vgurevich obviously, the compiler has internal names for these objects. I suspect what you want is a *predictable* way to name these objects that you can rely on. We could have a compiler flag that restricts P4 to a subset where some of these constructs are disallowed (e.g., instantiations in blocks).

@jphurl: indeed, the compiler does call PARSE for the standard annotations, and then it expects that the path expressions can be resolved. You don't have to use this parser, you can in principle write your own; you would probably have to extend the IR to represent the entities that you want to get our of your parser.

**Comment by mbudiu-vmw** [comment] 2021-06-29 01:04
I will assume we can close this issue

**Closed by mbudiu-vmw** 2021-06-29 01:04 UTC
Labels: question
