### ISSUE TITLE
Regarding compiler error for optional parameter

### ISSUE THREAD

**Issue by maheswari-s** [p4lang/p4c#2810] opened 2021-06-20 17:31 UTC
Getting error for an extern function that has type parameter with @optional.

Error message:
```
    -bash-4.2$ ./p4test test.p4
    test.p4(29): [--Werror=type-error] error: HwSplFunc: could not infer a type for variable R
            HwSplFunc(hdr.mac);
            ^^^^^^^^^^^^^^^^^^
    test.p4(9)
    extern void HwSplFunc<T, **R**>(in T hdr1, @optional in **R** hdr2);
                         ^
```

Is this a bug in compiler?
P4 Spec supports both ‘type parameter’ and @optional for a parameter: 

An example from P4 spec:
         package pack<HP, MP, HC, MC>(**@optional** parserProto<**HP, MP**> _parser,  // optional parameter
                                 controlProto<HC, MC> _control = nothing()); // default parameter value

Example is attached
[test.zip](https://github.com/p4lang/p4c/files/6682803/test.zip)

**Comment by mbudiu-vmw** [comment] 2021-06-21 20:34
The truth is that given the information you are providing the compiler has no way of guessing the type of R.
You could perhaps argue that it should infer a "don't care" type for R.
In the meantime you can help the compiler by providing a type explicitly:
`HwSplFunc<eth_t, _>(hdr.mac);`

**Comment by ChrisDodd** [comment] 2021-06-22 03:09
This looks like a duplicate of #2492 which had a fix merged for it, but perhaps it broke again?  We probably do not have adequate testcases

**Comment by mbudiu-vmw** [comment] 2022-01-20 02:13
It's not a duplicate, #2492 handles constructors, while this is a problem for functions.
Added some code that solves the problem in the same way.

**Closed** 2022-01-24 22:43 UTC
Labels: enhancement, fixed
