### ISSUE TITLE
CI failing to fetch opensuse packages p4lang-pi and p4lang-bmv2

### ISSUE THREAD

**Issue by ChrisDodd** [p4lang/p4c#5054] opened 2024-12-06 01:53 UTC
Looks like CI runs are all currently failing with errors like:

~~~~
Err:40 https://slc-mirror.opensuse.org/repositories/home:/p4lang/xUbuntu_20.04  p4lang-pi 0.1.0-15
  403  Forbidden [IP: 195.135.220.50 443]
Err:41 https://slc-mirror.opensuse.org/repositories/home:/p4lang/xUbuntu_20.04  p4lang-bmv2 1.15.0-7
  403  Forbidden [IP: 195.135.220.50 443]
E: Failed to fetch https://slc-mirror.opensuse.org/repositories/home:/p4lang/xUbuntu_20.04/amd64/p4lang-pi_0.1.0-15_amd64.deb  403  Forbidden [IP: 195.135.220.50 443]
E: Failed to fetch https://slc-mirror.opensuse.org/repositories/home:/p4lang/xUbuntu_20.04/amd64/p4lang-bmv2_1.15.0-7_amd64.deb  403  Forbidden [IP: 195.135.220.50 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
~~~

**Comment by fruffy** [comment] 2024-12-06 02:53
@rst0git

**Comment by fruffy** [comment] 2024-12-09 01:57
@ChrisDodd Looks like this was a spurious failure, but the opensuse packages fail frequently. We should switch to a more stable repository at some point.

**Comment by fruffy** [comment] 2024-12-12 19:30
Duplicate of https://github.com/p4lang/p4c/issues/4738

**Closed by fruffy** 2024-12-12 19:30 UTC
Labels: bug, infrastructure
