### ISSUE TITLE
Exception when trying to invoke apply() method of control instantiated at top level

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#436] opened 2017-04-05 04:06 UTC
I can instantiate a control A within control B, then invoke A.apply() within control B's apply block.  However, if I change it to instantiate A at the top level, the compiler crashes.  Not sure if this is intended to be a legal P4_16 program or not.

Look for occurrences of my_cBar in attached program.
[method-call-on-top-level-control-inst.p4.txt](https://github.com/p4lang/p4c/files/895153/method-call-on-top-level-control-inst.p4.txt)

**Comment by mbudiu-vmw** [comment] 2017-04-05 16:35
I think this is a duplicate of #388.
But this issue has a much better title.
Both of these are related to a spec issue: https://github.com/p4lang/p4-spec/issues/150
So we can't fix this one until we settle the problem in the spec.

**Closed** 2017-05-23 20:50 UTC
Labels: fixed
