### ISSUE TITLE
const entries does not work with typedef

### ISSUE THREAD

**Issue by awstuff** [p4lang/p4c#1834] opened 2019-03-28 07:19 UTC
I compiled the following program with the latest p4c version (for bmv2):

```
/* -*- P4_16 -*- */
#include <core.p4>
#include <v1model.p4>

struct headers { }

struct metadata {
    bit<8> test;
}


typedef bit<8> test_t;


parser ParserImpl(packet_in packet, out headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
    state start {
        transition accept;
    }
}


control IngressImpl(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
    action act(test_t a) { }    // does not work
    // action act(bit<8> a) { } // works

    table test_table {
        key = {
            meta.test: exact;
        }
        actions = {
            act;
        }
        const entries = {
            1: act(1);
        }
    }

    apply {
        test_table.apply();
    }
}


control VerifyChecksumImpl(inout headers hdr, inout metadata meta) {
    apply { }
}


control EgressImpl(inout headers hdr, inout metadata meta, inout standard_metadata_t standard_metadata) {
    apply { }
}


control ComputeChecksumImpl(inout headers hdr, inout metadata meta) {
    apply { }
}


control DeparserImpl(packet_out packet, in headers hdr) {
    apply { }
}


V1Switch(
    ParserImpl(),
    VerifyChecksumImpl(),
    IngressImpl(),
    EgressImpl(),
    ComputeChecksumImpl(),
    DeparserImpl()
) main;
```

When using `action act(bit<8> a) { }`, the program compiles without any problems, however, when using `action act(test_t a) { }`, the following output is produced:

```
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  In file: /home/p4/p4c/ir/type.def:337
Compiler Bug: Type_Name is not a canonical type, use getTypeType()?
```

**Comment by hesingh** [comment] 2019-03-28 13:06
The bmv2 backend does not support a struct as parameter to an Action.

**Comment by awstuff** [comment] 2019-03-28 13:46
To quote from the code above: `typedef bit<8> test_t;`

**Comment by hesingh** [comment] 2019-03-28 14:04
Wow, sorry, I assumed the `test_t` is a struct.  During the compiler's pre-processing, the typedef's should be replaced by a constant.  It would be good to include the command one used to see the problem.  I used your p4 program and do not see the issue.  I am using a fairly recent version of p4c.

```
hemant@ubuntu:/tmp/p4c/build$ ./p4c-bm2-ss --std p4-16 foo.p4 
tmpp.p4(23): [--Wwarn=unused] warning: Unused action parameter a
    action act(test_t a) { } // does not work
                      ^
hemant@ubuntu:/tmp/p4c/build$ 
```

**Comment by hesingh** [comment] 2019-03-28 14:18
I don't see the problem with the command you showed.  You should also use the new `--p4runtime-files` arg as shown in the warnings below.

```
hemant@ubuntu:/tmp/p4c/build$ ./p4c-bm2-ss --std p4-16 --target bmv2 --arch v1model --p4runtime-file tmp.txt --p4runtime-format text -o tmp.json foo.p4
[--Wwarn=deprecated] warning: '--p4runtime-file' and '--p4runtime-format' are deprecated, consider using '--p4runtime-files' instead
[--Wwarn=deprecated] warning: '--p4runtime-file' and '--p4runtime-format' are deprecated, consider using '--p4runtime-files' instead
foo.p4(23): [--Wwarn=unused] warning: Unused action parameter a
    action act(test_t a) { } // does not work
                      ^
hemant@ubuntu:/tmp/p4c/build$
```

**Comment by awstuff** [comment] 2019-03-28 14:22
I am running the most recent p4c version (commit `54de87dc08fba111cef4e6dd93b1597b1bf354f5`).

**Comment by jafingerhut** [comment] 2019-03-28 14:47
Using latest p4c, I do see the error.   Using the changes on this PR, which will hopefully be merged soon-ish, things seem to be working better and produce a correct p4info file: https://github.com/p4lang/p4c/pull/1792

**Comment by hesingh** [comment] 2019-03-28 14:53
Thanks, Andy.  Indeed, I was using my PR's repo https://github.com/p4lang/p4c/pull/1792/ and used `git pull` to pull latest p4lang/p4c and could not reproduce the issue.  

I am waiting on Antonin to complete review of my PR's latest code.

**Comment by awstuff** [comment] 2019-03-28 16:06
Thank you.

**Closed** 2019-05-30 17:40 UTC
Labels: bug, fixed
