### ISSUE TITLE
Warning "Direct counter not used; ignoring"

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4c#632] opened 2017-05-15 04:55 UTC
While compiling the file `testdata/p4_14_samples_outputs/counter.p4` the compiler produces the following message:
```
testdata/p4_14_samples_outputs/counter.p4(49): warning: my_direct_counter: Direct counter not used; ignoring
    @name("my_direct_counter") direct_counter(CounterType.bytes) my_direct_counter;
                                                                 ^^^^^^^^^^^^^^^^^
```
I do not believe this message is correct. This counter (my_direct_counter) is used in two actions (m_action_0 and _nop_0) and these actions are referenced in m_table that is, in turn, applied in control ingress.

I also saw this message appearing while compiling my own code, so it seems to be not limited to this file.

**Comment by jafingerhut** [comment] 2017-05-15 06:22
Probably a duplicate of https://github.com/p4lang/p4c/issues/461

**Comment by mbudiu-vmw** [comment] 2017-05-15 20:10
This is a duplicate of #461, already assigned to @ChrisDodd.
I will close this one.

**Closed by mbudiu-vmw** 2017-05-15 20:10 UTC
