### ISSUE TITLE
Question: Is preserving typedef type aliases on table key fields, action parameters, etc. reasonable to implement?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1157] opened 2018-02-07 21:49 UTC
In a few contexts when developing PSA, and now also in the P4 Runtime API working group, the observation has been made that it would be nice if an annotation could be placed on a typedef, e.g.:

```
typedef bit<13> PortId_t;
```
(Please mentally add one or more P4_16 annotations to the code above wherever they are syntactically legal -- I am being lazy and not looking that up right now.)

Then, wherever that type is used, e.g. for a field in a table's search key, or an action parameter, etc. the typedef name could be associated with it, and preserved in places like the P4Runtime Info file the compiler produces, and the P4 Runtime consumes.

My understanding is that right now, p4c treats typedefs as aliases for the underlying type, `bit<13>` in the example above, and it "forgets" the PortId_t type.

Is this "merely a convenience" for implementing the p4c compiler?  Something that in order to change, would require a change to the P4_16 language spec (and then the p4c implementation)?  Something else?

**Comment by mbudiu-vmw** [comment] 2018-02-08 17:19
I have a vague idea about what you mean, but to solve this issue we need a precise specification of what is desired. In general, if you have a declaration in your program, it is not guaranteed to map 1-1 to an object in the back-end. For example, the variable value may be constant-folded, or may be register allocated in a register which stores other values. So then there is no single object in the back-end that corresponds to the source declaration which could maintain source type information.

I think it is better to start from the problem that we need to solve by carrying type information around. Maybe we can state that more crisply?

**Comment by jafingerhut** [comment] 2018-02-08 17:53
Suppose I have a field in a table's key that is defined with type PortId_t (defined as `typedef bit<13> PortId_t`).  Right now P4Runtime Info will record that this is type `bit<13>` with no indication of anything about the named PortId_t.  It would be nice if it did, predictably, repeatably.

Same thing if such a value were used as an action parameter.

I can't think of any other desirable outcomes that aren't happening right now, but others might.

**Comment by jafingerhut** [comment] 2018-02-08 17:57
There may be other similar cases where such a value is an input value to some P4_16 extern, too, but the table keys and action parameters might be simplest to focus on first.

**Comment by mbudiu-vmw** [comment] 2018-02-08 18:17
Parameters are simpler, since they do not participate in optimizations.
Table keys are more problematic since they are expressions and the type of the expression is derived in general by the type-checker.
Is there a mechanism in P4Runtime to use symbolic type names?

Maybe what we need is a new kind of typedef which introduces a different type, which is not equivalent to the original one. E.g.:

```
newtype bit<12> Port_t;
```

This introduces a new type named Port_t which uses an underlying representation of a 12-bit. You cannot do anything to Port_t values except assign them and compare them for equality. 

This could also be a completely abstract type:

```
newtype Port_t
```

And then, when we have serializable types we can use that mechanism to specify how Port_t types are serialized.

**Comment by samar-abdi** [comment] 2018-02-08 18:22
Casting is also needed for PortId_t types.

**Comment by chrispsommers** [comment] 2018-02-08 18:47
Another way to state the problem:
Consider:
@type_hint("MAC_ADDR") typedef bit<48> mac_addr_t;

If a variable of type mac_addr_t is used as a match field or action param I'd like P4 info to be able to associate the annotation with the match field or action param, either by copying the annotation to the match field or action param's own annotation lists; or associating the match field or action param to a type; then we'd need to include (serialized) type information in the P4 info as well.

Similarly, consider:
header ethernet_t {
    @type_hint("MAC_ADDR") mac_addr_t dstAddr;

Then anytime an instance of .dstAddr is used in a match field or action param, I'd like P4info to convey that somehow too.

The alternative available today, is to annotate every match key and action param which gets cluttered. Also, multiple instances of this could become inconsistent; better to point back to the single source of truth in the typedef or header spec.

There was also discussion in the P4 API WG about establishing a defacto list of well-known types about which we could all agree and could comprise a standard include file. We'd still want to convey the type (name) references in p4info.

Even if we haven't figured out serializable types yet, we could attach type and annotation info from header specs and typedefs to the respective match fields and action params.

**Comment by mbudiu-vmw** [comment] 2018-02-08 19:06
You should not need to add a new type hint, the name you use for the type `mac_addr_t` should be sufficient to describe the type and bind it to other uses -- e.g. in the control-plane.

**Comment by mbudiu-vmw** [comment] 2018-02-08 19:08
The first step is to design P4info to carry this information.
The second step is to have a set of rules in P4 which indicate which types are "preserved".
For declarations it's easy, for expressions it's trickier.
We may need a new form of typedef - the existing one does not promise to preserve types.

**Comment by chrispsommers** [comment] 2018-02-08 19:12
Mihai, regarding 
"You should not need to add a new type hint, the name you use for the type mac_addr_t should be sufficient to describe the type and bind it to other uses -- e.g. in the control-plane."

I completely agree, as long as we establish at least a convention (or standard) of some well-known types about which we all agree.

For my example, let's assume some other annnotation was attached which we want to preserve.

**Comment by mbudiu-vmw** [comment] 2018-02-08 19:16
I can see why you would want annotations on types too.
The problem is that types are not really first-class objects in P4, we don't have a way to "compute on types". What we are saying here is that there are some operations which involve types - all of these are probably control-plane related. The data-plane should not care about how you named or annotated a type.

So the work should begin by identifying what control-plane operations need to convey type information. We may then need to make up a set of rules about how P4 compilers manipulate types. Today a typedef and the type it names are completely interchangeable. But what happens if you add two values typedefed from `bit<16>`? The spec does not say.

**Comment by chrispsommers** [comment] 2018-02-08 22:17
Mihai, It's not clear to me that control-plane operations themselves need to convey types, just the p4info needs to specify types where appropriate. Then the client and server both know what to do. The control plane messages just carry bits whose width is specified. Did I miss something?

**Comment by mbudiu-vmw** [comment] 2018-02-08 22:21
A type is a set of values and a set of operations.
`bit<48>` is a set of strings of 48 bits plus all the arithmetic and other stuff you can do on bitstrings.
But an ethernet address is also a set of strings of 48 bits, but with other operations.
So the fact the types are different is important. You do want to convey type information to the control-plane, to treat ethernet addresses differently. For example, you may allow a notation like `00:03:23...` for ethernet addresses but not for integers.

**Comment by chrispsommers** [comment] 2018-02-08 22:26
I appreciate the explanation of what a type is to the compiler. I'm not sure the control plane needs to understand all that. But it would want to know user-side representations like IP and MAC addresses, or allowed values for enums with specific values (not yet even possible inthe  language). I wonder what others have to say on this?

**Comment by mbudiu-vmw** [comment] 2018-02-08 22:41
It's not just about the compiler, it's about any piece of software, including the control-plane.
We need to expose different types in P4 differently to the control-plane.

**Comment by jafingerhut** [comment] 2018-03-23 18:32
If I understand correctly, I am warming up to the idea of "newtype bit<13> PortId_t", where:

+ values of this type would only be able to be assigned to each other, compared for equality or inequality to each other.  Samar Abdi mentions the desire to be able to cast bit<13> values to PortId_t and vice versa.  I am not yet sure why this is desired, but I cannot think of any objections to allowing explicit casts of values with these newtype types, at least between the "base type" (bit<13> in this example) and the newtype PortId_t.  Restricting the operation set is potentially to only these might be desirable in order to prevent P4 programmers from accidentally doing inappropriate comparisons / arithmetic on values of these new types where it would likely be a functional bug to do so.  Allowing explicit casts to the base type gives the P4 programmer to do it anyway, if they really want to and know what they are doing.

+ The type name "PortId_t" would be preserved wherever values of that type are used, at least in the P4Info file, including: as action parameters, as key fields, as elements of tuples for externs like Digest and hopefully also Register, etc.

+ Mihai, you mention that key fields are actually expressions.  If these newtype values are restricted to only assignment and == !=, then it should be reasonable for it to be a compiler-detected error if someone tried to use a bitwise AND mask expression with a value of such a type, true?  So that concern of yours is hopefully addressed by the restriction on operations allowed on values with a newtype type?

**Comment by mbudiu-vmw** [comment] 2018-03-23 19:25
Yes, I think this description is correct.
One other possible design choice is for the new type to inherit all operations of the old type, but just disallow mixing values of different types in the same expression without casts.

**Comment by jafingerhut** [comment] 2018-03-23 20:12
@samar-abdi @chrispsommers Just pinging your Github id here as a recommendation to read my last comment before this one, and follow up if you wish.

**Comment by ChrisDodd** [comment] 2018-03-23 20:43
How is this `newtype` different from something like

    struct PortId_t { bit<13> value; }

This gives you a new type name (`PortID_t`) that can be copied and (I believe we added) compared for equality.

**Comment by mbudiu-vmw** [comment] 2018-03-23 20:45
The field name is rather redundant.
Also, if you want to allow + later you won't be able to do it nicely on structs.

**Comment by jafingerhut** [comment] 2018-03-23 21:26
@ChrisDodd I agree that what you propose would very likely get the minimum job done, and perhaps should be considered for this purpose.  Long term, it feels like kind of a workaround, but maybe that is OK, too.

**Comment by jafingerhut** [comment] 2018-03-23 22:02
Sorry, accidentally hit the "Close" button, then reopened.

@ChrisDodd A wrinkle with that approach is that if one wants to match on type PortId_t as a field in a table's key, and/or use a PortId_t as an action parameter, I don't think the current P4Runtime spec supports those right now.

I realize in saying this that the "newtype" proposal also has that problem, and more, since it is not even in the language spec yet, so treat that observation with the weight it deserves.

**Comment by samar-abdi** [comment] 2018-03-23 22:32
An important use case is including PortId_t fields in headers. This is how P4Runtime deals with packetio metadata. IIRC structs are not allowed in headers. Newtype seems like a good option; and until then we can compromise by annotating all usage of PortId_t.

@jafingerhut Casting is needed for going back and forth between PortIdInHeader_t fields and PortId_t fields in the dataplane.

**Comment by jafingerhut** [comment] 2018-03-24 00:25
@samar-abdi Until then, it is annotating all usages of all 7 of these types, not only PortId_t, yes?

    https://p4.org/p4-spec/docs/PSA-v1.0.0.html#sec-psa-type-definitions

Or at least annotating all usages in places that affect the contents of the P4Info file, which is: as table key or parser value set key, as action parameter, as an extern argument.

Out of curiosity, do you know what the effect would be of forgetting one of the needed annotations with the annotate-everything interim solution?  Would it be silently incorrect table entry contents?  A P4Runtime run time error on an attempted control plane operation?  Something else?

**Comment by samar-abdi** [comment] 2018-03-24 02:20
IMO only port and cos may have values that are intrinsic to the device and are out of the control of the controller. Multicast group id, clone session id and egress instance ids are anyway chosen by the controller and it can use the largest bitwidth supported by all targets it controls. Packet length and timestamps "should" be uniform across devices, so I don't expect requiring translation for them.

If we forget the annotation, it will lead to P4Runtime errors when the controller sends down 4 bytes (for a 32-bit port) and the P4Runtime service expects only 2 bytes (corresponding to 9 - 16 bit ports which is typical case). Of course, if the device port type is >24 bits, it will be a silent error in this case.

**Comment by jafingerhut** [comment] 2018-03-24 03:52
@samar-abdi Just to make sure we are on the same expectations here, my expectation is that two devices might both implement PSA v1.0, where one supports MulticastGroup_t values in the range [0, 16383], and return an error if a controller attempts to use any value larger than 16383, and another might support values for that type in the range [0, 24575], and return an error if a controller attempts to use any value larger than 24575.  Does that match what you are expecting?

Similarly, I expect there could be some PSA devices with 40-bit Timestamp_t values, and others that have 44-bit Timestamp_t values.  I am not sure if that fits with your idea of "uniform" or not.

**Comment by samar-abdi** [comment] 2018-03-25 05:18
@jafingerhut Your expectation matches mine for multicast group. In the SDN case the max value of the multicast group ID is the least of the max value allowed across devices.

As for timestamp, you have a valid point. The value in the device might be based off of some free running counter incremented at the ASIC's normalized clock speed (accounting for DVFS), so it may have no bearing to the clock speed in the controller.   So, yes timestamps will also require translation. Like for ports, I believe switch config is the right place to put expected value of timestamp increment rate and the controller's timestamp bitwidth. The P4Runtime service should refer to these config values when doing the translation.

**Comment by jafingerhut** [comment] 2018-03-27 18:35
@ChrisDodd You mentioned an idea in the hallway to me after the 2018-Mar-26 language design work group meeting that might be useful here.  Could you add a comment describing it further?  I neglected to write it down, and do not remember it in enough detail to describe it.

**Comment by ChrisDodd** [comment] 2018-03-27 18:48
The problem with annotations on a typedef (`@port_id typedef bit<7> Port_id_t;` or whatever) is that the typedef type (and thus the annotation) is lost by the time you get to any expression involving uses of this type.  One way to avoid that (one way to make annotations on typedefs useful) would be to say that an annotation on a typedef type is inherited by any variable or field declared with that typedef type name -- in the parser we just copy those annotations to the var/field immeidately (appending to any other annotations that var/field might have).

This gives us the ability to have an annotation that need only appear literally in the arch header file, but applies to many places in the user's file, without forcing the user to add lots of annotations.  I think this gives us the ability address the issues/goals without having to add a new keyword or new typing rules.

**Comment by ChrisDodd** [comment] 2018-03-27 18:51
Note that since the annotation is on a field or var, this still leave us questions what to do about expressions that involve multiple fields or are otherwise complex, but that is the same question as default names for key expressions (which we resolved as only being for direct references of fields -- any more complex expression would require the use to add an annotation to the key).

**Comment by antoninbas** [comment] 2018-03-27 19:00
I actually really like @ChrisDodd original proposal, which was to wrap the translated values into a struct (https://github.com/p4lang/p4c/issues/1157#issuecomment-375792852). I think it is a very elegant solution which has the advantage of "preventing" arithmetic operations on the type (unless you choose to access the field inside the struct, which would mean to me that you know the risks).

It reminds me of the common C technique to hide the implementation of a type:
```
typedef struct _Point Point;
struct _Point
{
   int X;
   int Y;
};
```

Of course we cannot do exactly that in P4, but I believe it is a similar idea.

@jafingerhut why does it feel too much like a workaround to you?

**Comment by chrispsommers** [comment] 2018-03-27 19:19
@ChrisDodd I think my comment https://github.com/p4lang/p4c/issues/1157#issuecomment-364210092 expresses this sentiment also - annotate the type and let it propagate.

**Comment by samar-abdi** [comment] 2018-03-27 19:20
The problem with struct is that it will also require language change. We can't have structs inside headers. If annotations can be carried, it will achieve the same capabilities as newtype.

**Comment by mbudiu-vmw** [comment] 2018-03-27 19:41
Another problem is that today expressions cannot have annotations. Even if they could in the IR, it may be difficult to serialize these back to P4.

**Comment by antoninbas** [comment] 2018-03-27 20:01
@samar-abdi I'm not sure why it is a problem in this case. You are supposed to use the PSA `InHeader_t` types inside headers, not `PortId_t` etc.
It would force you to write something like `hdr.port = (PortInHeader_t)meta.port._v` but IMO that's not bad since you have to be aware of the risks when writing a port value to a header.

**Comment by jafingerhut** [comment] 2018-03-27 20:15
@antoninbas I think @samar-abdi's point is that you can't have a field in a to-CPU header with type PortInHeader_t, if PortInHeader_t is defined as `struct PortInHeader_t { bit<32> value; }`, because P4_16 spec today does not allow structs to be fields of a header.

**Comment by jafingerhut** [comment] 2018-03-27 20:18
@mbudiu-vmw I understand the point about expressions, but even if only fields and metadata variables with a type of PortId_t had the annotations propagated to them, I think that would eliminate all annotations in most P4 programs using types PortId_t and ClassOfService_t in the ways they typically would.  For example, even though expressions are allowed as part of a table key, that capability is rarely used in most P4 programs I have seen.

**Comment by antoninbas** [comment] 2018-03-27 20:21
My understanding was that `PortInHeader_t` would not need to be defined as a struct?

`PortInHeader_t` is the portable type and only `PortId_t` needs to be defined as a `struct`. In this code snippet: `hdr.port = (PortInHeader_t)meta.port._v`, `hdr.port` has type `PortInHeader_t` which is `bit<32>`, while `meta.port` has type `struct PortId_t { bit<9> _v; }`. (I'm picking a bitwidth of 9 as an example).

**Comment by antoninbas** [comment] 2018-03-27 20:32
@samar-abdi I see your point. Seems to me though that we could annotate the 2 instances of `PortInHeader_t` variables that needs to be translated (in packet-in and packet-out headers), since we would be using `struct PortId_t` everywhere else anyway. Unless you think that there would be more occurrences of `PortInHeader_t` in the program. It would also potentially let me choose which `PortInHeader_t` instances to translate, should the need arise (for some dataplane-to-dataplane packets for example).

That's just a thought so, since I think the introduction of a struct helps with enforcing that port values are not used in a non-sensical fashion in the P4 program.

**Comment by jafingerhut** [comment] 2018-03-27 21:57
I probably will not get to it for a another week or so, but I plan to take the various suggestions given so far and summarize them, hopefully with code examples showing what would be different between them.  I suspect it will be too difficult to compare them without something like that.

So far the main proposals I know about are:

+ default is no changes to the language, leading to potentially many annotations in P4 programs required for the generated P4Info file to be correct
+ `newtype`
+ `struct PortId_t { bit<W> value; }`
+  typedef annotations being propagated to fields and variables of that type, but not to expressions involving those types

**Comment by mbudiu-vmw** [comment] 2018-03-27 22:08
The main problem with expression is the substitution principle, which allows the compiler to replace equals with equals. If the compiler things two variables (or expressions) have the same value at the same time, the compiler can substitute the use of one with the other. 

The problem with treating some expressions specially is that an expression with an annotation is no longer exactly equal with another expression without the annotation. That is very subtle and brittle, and I would really like to avoid making such assumptions in the language definition or implementation.

E.g.

```
@special typedef bit<32> X;
...
X a;
bit<32> b;
...
a = b;
function(a);  /// here the compiler should be able to use b instead of a. 
```

If the function behavior is impacted by the annotation being present on a, then a and b are not really interchangeable anymore.

**Comment by jafingerhut** [comment] 2018-03-27 22:56
I _believe_ that the motivating use case that originated this issue is the ability for the compiler to generate a P4Info file with table key fields, action parameters, and some extern arguments (e.g. Digest, Register) to have the annotation on them, so the P4Runtime software knows to do numerical translation on those during control plane operations.

As far as I know, the propagation of these annotations should have 0 effect on the data plane run time behavior.

@mbudiu-vmw Assuming for the moment that the beliefs above are true, are you still concerned that the compiler would be restricted in unnatural ways by the typedef annotation propagation idea?

**Comment by mbudiu-vmw** [comment] 2018-03-27 23:02
Yes, I am concerned about everything that can be an expression in the grammar. If the objects you enumerated above would be restricted to identifiers we would be in a better shape - from an identifier you can find its declaration, and the declaration has the type, which has the annotation. So the algorithm to find the type annotation is very clear for identifiers.

I really don't like subtle hacks, in the long term they can hurt you badly. I find propagating annotations from types to expressions in this category.

The `newtype` proposal is heavyweight, but it also adds a mechanism which can be valuable for other things - an abstract type.

**Comment by jnfoster** [comment] 2018-03-28 15:12
I agree with Mihai that subtle hacks tend to be dangerous. They interact in
unexpected ways and lead to big problems down the road.

I am nervous about having a generative types. For instance, type inference
may become much less predictable and intuitive, since a given expression
could now have multiple types depending on whether the underlying bit type
or the newtype'd identifier is inferred (in a sense for reasons that are
similar to the issue with expressions under the annotation approach).
Perhaps its enough to infer the bit type unless the newtype'd identifier
was referenced, but this seems arbitrary and it may discard a key property
that makes type inference so great -- principal types!

I mentioned this at the P4 LDWG, but it strikes me that tweaking the
data-plane level type system to fix a control-plane problem may be the
wrong approach. Stepping back, what we are *really* after is a way to
specify and precisely control the types that appear in the control-plane
interface. Perhaps similar to Java Interfaces or ML module signatures, the
language should provide a mechanism for a programmer to specify the
external interface of a P4 program. This interface might hide certain
implementation details and/or expose different names/types than the ones
that the compiler would generate fro the program.

**Comment by samar-abdi** [comment] 2018-03-28 16:54
@jnfoster IMHO The larger problem is one of abstraction.

The PSA interpretation of the P4 program is that it is a model of the switching device. The control plane would like to program to a model of the logical dataplane pipeline that is common across all switches it controls. Some of which may even be implemented in the switch software! Ports is an example where there is a disconnect between control plane view and device view; so we are trying to bridge this through standard annotations.

If the P4 program were treated as an abstract model of the switch (not device), if will become the P4 compiler and P4Runtime service's problem to translate port numbers and other intrinsic metadata from the abstract controller view to device specific view. The map for this translation will still come through the switch config and we will still need to limit the types of operations we can perform on intrinsic metadata (eg. no arbitrary masks in ternary match).

Either approach is OK as long as the semantics of intrinsic metadata are clearly spelled out.

**Comment by jafingerhut** [comment] 2018-03-28 18:36
@jnfoster said: "I mentioned this at the P4 LDWG, but it strikes me that tweaking the
data-plane level type system to fix a control-plane problem may be the
wrong approach. Stepping back, what we are *really* after is a way to
specify and precisely control the types that appear in the control-plane
interface. Perhaps similar to Java Interfaces or ML module signatures, the
language should provide a mechanism for a programmer to specify the
external interface of a P4 program. This interface might hide certain
implementation details and/or expose different names/types than the ones
that the compiler would generate fro the program."

Today the external interface of a P4 table is auto-generated from the P4 source code definition of the table (at least, it seems to me that this is the case), without needing anything outside of the P4 source code.

Would this suggestion be something like: For _every_ P4 table in the source code, something outside of the `table my_table_name { ... }` would specify its control plane interface?

Or would it be that today's current method is used by default, and only when you want to customize that interface do you need to write something in the source code, outside of the `table my_table_name { ...}` part of the source file?

Since these 2 or 3 types we want numerical translation for in PSA right now, can appear as any field of any table key, or as any action parameter of any action, I don't see how even the last approach above helps reduce the _quantity_ of extra code you must write to generate the control plane interface.  It seems like it could even be more than the existing "annnotate the field wherever it appears, even if it appears 10 times in the program", because now you would need to say "oh, by the way, for all of those fields that we want to do the normal thing for bit<7> types, do the normal thing, not the special-translation option thing".

Is there a proposed syntax that would be _less_ duplication of intent than the "annotate the field wherever it appears, as often as it appears"?

**Comment by samar-abdi** [comment] 2018-03-28 19:13
@antoninbas I like the idea of using annotated PortInHeader type ports in the packet-io header and using struct elsewhere. Can you please give example of how a match key and action will look like with this struct?

**Comment by antoninbas** [comment] 2018-03-28 19:15
@samar-abdi I'll upload an example program later today which hopefully covers all use cases

**Comment by antoninbas** [comment] 2018-03-28 21:26
@samar-abdi here is what I had in mind (this is not a complete program, but hopefully it covers a lot of aspects of using port values in a P4 program):
```
// From psa.p4

#define PORT_BITWIDTH 9  // target-specific

#define PSA_CPU_PORT 9w192;  // target-specific

// rest is target-independent

// request translation by P4Runtime agent of all occurrences of PortId_t exposed
// to control-plane
@p4runtime_translate("port")
struct PortId_t { bit<PORT_BITWIDTH> _v; }

// used to cast between PortId_t and PortInHeader_t; the programmer needs to be
// aware that he may be exposing non-translated values to the control-plane,
// unless he use @p4runtime_translate appropriately
#define PORT_HEADER_TO_ID(p) ({(bit<PORT_BITWIDTH>)p})
#define PORT_ID_TO_HEADER(p) ((PortInHeader_t)p._v)

typedef bit<32> PortInHeader_t;

// From fabric.p4

@controller_header("packet_in")
header packet_in_header_t {
    @p4runtime_translate("port")  // request translation by P4Runtime agent
    PortInHeader_t ingress_port;
}

@controller_header("packet_out")
header packet_out_header_t {
    @p4runtime_translate("port")  // request translation by P4Runtime agent
    PortInHeader_t egress_port;
}

control PacketIoIngress(
inout parsed_headers_t hdr,
inout fabric_metadata_t fabric_metadata,
inout standard_metadata_t standard_metadata) {
    apply {
        if (hdr.packet_out.isValid()) {
            // I know what I'm doing, I requested translation on
            // packet_out.egress_port
            standard_metadata.egress_spec =
                PORT_HEADER_TO_ID(hdr.packet_out.egress_port);
            hdr.packet_out.setInvalid();
            exit;
        }
    }
}

control PacketIoEgress(
inout parsed_headers_t hdr,
inout fabric_metadata_t fabric_metadata,
inout standard_metadata_t standard_metadata) {
    apply {
        // struct-comparison is valid
        if (standard_metadata.egress_port == PSA_CPU_PORT) {
            hdr.packet_in.setValid();
            // I know what I'm doing, I requested translation on
            // packet_in.ingress_port
            hdr.packet_in.ingress_port =
                PORT_ID_TO_HEADER(standard_metadata.ingress_port);
        }
    }
}

control Filtering (
inout parsed_headers_t hdr,
inout fabric_metadata_t fabric_metadata,
inout standard_metadata_t standard_metadata) {
    table t {
        key = {
            // translated by P4Runtime agent because of annotation on PortId_t
            standard_metadata.ingress_port: exact;
        }
        action = { drop; nop; }
    }

    apply { t.apply(); }
}

control Forwarding (
inout parsed_headers_t hdr,
inout fabric_metadata_t fabric_metadata,
inout standard_metadata_t standard_metadata) {
    // next_port translated by P4Runtime agent because of annotation on PortId_t
    action fwd(Port_t next_port) {
        standard_metadata.egress_spec = next_port;
    }

    table t {
        key = {
            hdr.ipv4.dstAddr : exact;
        }
        action = { drop; fwd; }
    }

    apply { t.apply(); }
}

control FabricIngress (
inout parsed_headers_t hdr,
inout fabric_metadata_t fabric_metadata,
inout standard_metadata_t standard_metadata) {
    PacketIoIngress() packet_io_ingress;
    Filtering() filtering;
    Forwarding() forwarding;

    apply {
        packet_io_ingress.apply(hdr, fabric_metadata, standard_metadata);
        filtering.apply(hdr, fabric_metadata, standard_metadata);
        forwarding.apply(hdr, fabric_metadata, standard_metadata);
    }
}

control FabricEgress (inout parsed_headers_t hdr,
                      inout fabric_metadata_t fabric_metadata,
                      inout standard_metadata_t standard_metadata) {
    PacketIoEgress() pkt_io_egress;
    apply {
        pkt_io_egress.apply(hdr, fabric_metadata, standard_metadata);
    }
}

V1Switch(
    FabricParser(),
    FabricVerifyChecksum(),
    FabricIngress(),
    FabricEgress(),
    FabricComputeChecksum(),
    FabricDeparser()
) main;
```

**Comment by jnfoster** [comment] 2018-03-29 00:57
@jafingerhut the idea would be to have a separate independent description of the interface that would be *checked* for compatibility with the auto-generated interface from the code. If the two are always identical, then I agree this is always redundant. But as we are seeing, often they are not. Here we want to change the type PortId_t. In other settings, we may want the interface to stay stable even as we refactor the internal structure of the code -- e.g., abstracting out common functionality into a control that is instantiated several times, which changes the names of the tables and other elements. 

While DRY is generally a good principle, plenty of other language have found value in separating specification and implementation. I suspect we will reach the same conclusion if we follow this line of thinking. And with good syntactic support, we can likely greatly reduce the burden of writing out interfaces.

**Comment by samar-abdi** [comment] 2018-03-29 17:19
@antoninbas Thanks for the example!! It makes a lot of sense.

Just to be clear, are you proposing that @p4runtime_translate is only allowed in header fields in your proposal, and a P4Runtime compliant target's compiler will check for it? In other words, we are explicitly disallowing two different signals for the P4Runtime service to invoke translation.

Related, in P4Info, the bitwidth will appear as 32 bits for all PortId_t (struct) instances?

**Comment by samar-abdi** [comment] 2018-03-29 18:48
@antoninbas SGTM! Perhaps, we should have a PSA and P4 API joint meeting with this proposal.

Calling out @teverman to review this as well.

**Comment by antoninbas** [comment] 2018-03-29 20:30
@samar-abdi that would be good, maybe @jafingerhut can help set something up

**Comment by jafingerhut** [comment] 2018-04-04 02:24
Sorry I have not gotten to setting something up yet, but after whatever discussion there is at P4-API working group meeting on Apr 4 2018, I can set something up to discuss the `struct PortId_t { bit<W> value; }` idea with an interested sub-group, at least for P4Runtime v1.0.

Among the 4 options I listed in this earlier comment: https://github.com/p4lang/p4c/issues/1157#issuecomment-376689265 I later realized that the `struct` approach can be considered as one way of creating a new type, like the `newtype` idea, except it does not require any additions to the language spec, so it does have that "not far from where we are now" aspect going for it.

**Comment by jafingerhut** [comment] 2018-04-13 22:15
The people listed below had a 1 hour meeting on 2018-Apr-12 to discuss this issue.

+ @jafingerhut @vgurevich @ChrisDodd @mbudiu-vmw 

A couple of people from P4Runtime were not available for this meeting, but I will schedule another some time next week where hopefully they can also make it.

If you were there, feel free to add your own comment with any additions or corrections.

We mostly went through the first 2 "goals" slides of the linked-to presentation, and discussed and clarified what was meant by them: https://github.com/jafingerhut/p4-guide/blob/master/docs/p4runtime-and-psa-target-specific-types.pptx

Vladimir had a good line to summarize the goal here: we want a way to define a type like `PortId_t` (and a few other similar types now, and probably more in the future), where it behaves like one type in the data plane, e.g. `bit<W>` where the value of W isn't even explicitly in the data plane code anywhere, but as `bit<32>` to the control plane.  

I would add: Not only as `bit<32>` to the control plane, but as `PortId_t`, along with any annotations associated with _the type declaration for PortId_t_ would be best, so that the annotation is guaranteed to "follow" all occurrences of variables (and maybe also expressions) of that type, everywhere they occur in a P4 program.

Vladimir: A similar and useful goal is: even if the bit widths are identical in the data plane and control plane, enable defining a type like `IPv4Address` where the P4Info file would represent that the type was `IPv4Address`, not only `bit<32>`.

Andy's concern: The way `typedef` works in the open source p4c compiler today, it seems to me that it is a fruitless approach to use `typedef` to define `PortId_t` with these properties, because of Mihai's example here: https://github.com/p4lang/p4c/issues/1157#issuecomment-376692097

Unless I am misunderstanding something fundamental (and I very well could be), in order for a type `PortId_t` to be accurately tracked through a P4 program, and through a P4 compiler's transformations that it might do on intermediate representations, it seems that values of type `PortId_t` should be _never_ equal to values of any other type.  If they could be equal to values of other types, then intermediate steps of the compiler would be free to substitute values of other types that were equal (i.e. `==`) to it, and you would lose the fact that it was type `PortId_t`.  It is OK if there is a way to cast values of type `PortId_t` to values of other types and back, perhaps, but it shouldn't be done implicitly without explicit casts.

Either the previous paragraph is correct, or perhaps another way forward is to say that whatever portion of a P4 compiler produces a P4Info file that contains data about the control plane interface to a particular P4 program, that part of the compiler must never do the kinds of transformations that could cause these types and annotations to be erased or modified.

**Comment by mbudiu-vmw** [comment] 2018-04-13 23:12
I don't know if the issue is the place to carry out an elaborate design discussion.
Other things we have done are to: clarify who performs this translation, and to establish that if one wants to have different things, they have to have different names (e.g., there should be two different types in PSA.p4 to indicate the dataplane port type and the control-plane view of the port type).

**Comment by vgurevich** [comment] 2018-04-14 16:13
@jafingerhut ,

> Unless I am misunderstanding something fundamental (and I very well could be), in order for a type PortId_t to be accurately tracked through a P4 program, and through a P4 compiler's transformations that it might do on intermediate representations, it seems that values of type PortId_t should be never equal to values of any other type.

I think that in practice this is a relatively constrained problem. So far, the only place that would really require good tracking are the table keys and only in case one uses expressions and specifically the expressions that have a potential to mix things. The three most important forms of expressions that cover 99.9% of everything I've see written so far are:
# An individual field: `h.ipv4.dstAddr`
# A bit-slice of the said field: `h.ipv4.dstAddr[31:24]`
# The validity check: `h.ipv4.isValid()`
For all these I think it is very clear how to derive the control plane type automatically. 

For the others, @mbudiu-vmw has proposed a solution, where you can specify the desired control plane type and name in the table via:
```
table t {
   keys = {
       PortId_t   next_port = m.ingress_port + 1: exact;
   }
   . . . 
}
```
There is no need to do tracking for actions, since action parameter types are explicitly specified in the code (unless the compiler immediately drops them to the primitive types).

This does leave value_sets out, but so far we do not know how we will be specifying the control plane names and types there in the first place.

This also leaves open the question what should debug tools do, since they can have visibility into expressions and other things that "traditional" control plane APIs can't see, but I think the requirements there are not as stringent and it would probably be OK to always "drop" to a fundamental P4 type or use heuristic resolution. In the worst case, the user of the debugging tool will be able to choose the desired representation interactively.

**Comment by jafingerhut** [comment] 2018-04-16 17:47
@mbudiu-vmw I believe that the elaborate part of the design discussion is occurring more in live meetings than here.  This list of comments seemed like a quick convenient place to record some brief notes from those meetings, not all of the details.  The decided-upon details should definitely be documented elsewhere.

@mbudiu-vmw @ChrisDodd @antoninbas I have a question regarding Mihai's example code here https://github.com/p4lang/p4c/issues/1157#issuecomment-376692097 and the issue of a compiler being free to substitute equal expressions for equal expressions anywhere it wants during the back end.

I agree a compiler should be free to make such transformations, but is that perhaps a non-issue for the purposes of generating a P4Info file from a P4 source program?  Yes, we want to reuse a compiler's P4 parser when generating a P4Info file, but shouldn't the P4Info file be generated after very few, or _no_, transformations of the intermediate representation after that parsing is complete?  If so, it seems we can drastically limit the kinds of compiler transformations that we need to consider that might otherwise "break" our chosen approach for this issue.

Can you think of any reason why a program wanting to generate a P4Info file that contained only things like those below would need any transformations on the output of the compiler's parser?

+ a list of table, action, and extern names
+ for each table, the names, types, and match_kind's of its key fields, and its list of actions
+ similarly short lists of information about actions and externs, i.e. no details about action bodies, only their parameter names and types.

**Comment by mbudiu-vmw** [comment] 2018-04-16 17:50
This is how table keys are handled: a very early pass attaches name annotations to table keys, and then the compiler is free to change the expressions for table keys.
But still, we need rules about annotations moving from types to expressions.

**Comment by mbudiu-vmw** [comment] 2018-07-16 17:18
I believe that the newtype (`type`) in P4-16 v1.1.0 addresses this issue. Can we close it?

**Closed** 2018-08-14 00:50 UTC
Labels: enhancement, fixed
