### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Safaamahrach** [p4lang/p4c#1405] opened 2018-07-17 15:59 UTC
salam

Please I'm trying to get started with p4-16, I'm using the official link 
https://github.com/p4lang/p4c

I'm in Building step with the following commands:
mkdir build                            //I create  the folder in p4c directory
cd build
cmake .. [-DCMAKE_BUILD_TYPE=RELEASE|DEBUG] [-DCMAKE_INSTALL_PREFIX=</home/safaa/Downloads/p4c>] [-DENABLE_DOCS=ON (default off)] [-DENABLE_P4RUNTIME_TO_PD=OFF (default on)] [-DENABLE_PROTOBUF_STATIC=OFF (default on)] [-DENABLE_GC=OFF (default on)]

WHEN I use the above cmake command it gives me an error as you can see bellow and in the attached-image 
CMake Error: The source directory "/home/safaa/Downloads/p4c/build/[-DENABLE_GC=OFF]" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
![cmake error](https://user-images.githubusercontent.com/31244674/42830047-78565620-89e2-11e8-8087-e2aa6f51c047.png)

Thanks for your help

**Comment by ChrisDodd** [comment] 2018-07-17 16:31
duplicate of #1356?

The brackets (`[`...`]`) denote optional arguments to cmake -- you need to decide which ones (if any) you need.  In the simplest case, to get the defaul behavior, you can use just

    cmake ..

**Closed** 2018-08-14 00:47 UTC
Labels: duplicate, question
