### ISSUE TITLE
ConstantFolding not folding as expected

### ISSUE THREAD

**Issue by jphurl** [p4lang/p4c#2585] opened 2020-10-14 01:25 UTC
For something like this:
```p4
h.data = h.data2 - 8 - 8 - 2 - 16;
```
I would expect `ConstantFolding` to fold this to:
```p4
h.data = h.data2 - 34;
```
however, it does not fold the constants at all.

If parens are added:
```p4
h.data = h.data2 - (8 + 8 + 2 + 16);
```
then the constants are folded as expected.

test: 
[constant-fold.p4.txt](https://github.com/p4lang/p4c/files/5375005/constant-fold.p4.txt)

**Comment by mbudiu-vmw** [comment] 2020-10-14 01:27
This is a duplicate of https://github.com/p4lang/p4c/issues/1149
The optimization we need is called "reassociation": https://stackoverflow.com/questions/23827531/reassociation-according-to-muchnick

**Closed** 2020-10-15 17:17 UTC
Labels: duplicate, fixed
