### ISSUE TITLE
Type Checking error when using <int> vs <bit> type

### ISSUE THREAD

**Issue by amreshk** [p4lang/p4c#2384] opened 2020-05-18 19:26 UTC
Consider the following program,

```
#include <v1model.p4>

header Ethernet {
    bit<48> src;
    bit<48> dest;
    bit<16> tst;
}

struct Headers {
    Ethernet eth;
}

parser prs(packet_in p, out Headers h) {
    state start {
        transition accept;
    }
}

control c(inout Headers h, inout standard_metadata_t sm)(int pprio) {
    action do_act() {
    }

    @pragma custom_annot pprio
    table tns {
        key = {
            h.eth.tst[13:4] : exact;
        }
    actions = {
            do_act;
        }
    }

    apply {
        tns.apply();
    }

}

control ctop(inout Headers h, inout standard_metadata_t sm)(int pprio) {
    standard_metadata_t sm;
    c(pprio) c1;
    apply {
        c1.apply(h, sm);
    }
}
parser p<H>(packet_in _p, out H h);
control ctr<H, SM>(inout H h, inout SM sm);
package top<H, SM>(p<H> _p, ctr<H, SM> _c);

top(prs(), ctop(1)) main;
```

Compiler output:

```
Compiler Bug: test.p4(41): Could not find type of @name("c1") c c1_0/c1(1)
    c(pprio) c1;
             ^^
```

Pass where the issue occurs,

```
FrontEnd invoking SpecializeAll
  SpecializeAll invoking ConstantFolding
    ConstantFolding invoking P4::TypeChecking
      P4::TypeChecking invoking ResolveReferences
      P4::TypeChecking invoking P4::TypeInference
    ConstantFolding invoking DoConstantFolding
    ConstantFolding invoking P4::ClearTypeMap
  SpecializeAll invoking P4::TypeChecking
    P4::TypeChecking invoking ResolveReferences
    P4::TypeChecking invoking P4::TypeInference
  SpecializeAll invoking FindSpecializations
  SpecializeAll invoking Specialize
  SpecializeAll invoking RemoveAllUnusedDeclarations
    RemoveAllUnusedDeclarations invoking PassRepeated
      PassRepeated invoking ResolveReferences
      PassRepeated invoking RemoveUnusedDeclarations
      PassRepeated invoking ResolveReferences
      PassRepeated invoking RemoveUnusedDeclarations
  SpecializeAll invoking ConstantFolding
    ConstantFolding invoking P4::TypeChecking
      P4::TypeChecking invoking ResolveReferences
      P4::TypeChecking invoking P4::TypeInference
In file: /mnt/p4c/frontends/p4/typeChecking/typeChecker.cpp:168
Compiler Bug: test.p4(41): Could not find type of @name("c1") c c1_0/c1(1)
    c(pprio) c1;
             ^^
```

NOTES:

The above program does not throw a compiler bug when `int pprio` is changed to a bit type `bit<32> pprio`.

This is observed only when the control is being invoked by a top level control. The issue does not appear when we have only 1 control in the program and are using `int pprio`.

**Comment by fruffy** [comment] 2020-05-19 12:50
I think this might have already been fixed by https://github.com/p4lang/p4c/pull/2337.

At least with compiler version:

```
fruffy@fruffy /m/w/P/p4_tv (another_attempt)> p4c/build/p4test --version                          
p4c/build/p4test                                                                                  
Version 1.2.0 (SHA: 20400f5b6 BUILD: RelWithDebInfo)
```
I cannot reproduce this any more.

**Comment by mbudiu-vmw** [comment] 2020-05-19 18:03
I have tagged this as invalid.

**Closed** 2020-05-29 17:38 UTC
Labels: invalid
