### ISSUE TITLE
default value for package parameter not supported.

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#1639] opened 2018-12-19 23:39 UTC
The following program failed to compile with error. It is similar to the example given in spec 6.7.2. Optional parameters

```
package P<H, M>(C<H, M> c = nothing());
                        ^
/Users/hanwang/p4c/testdata/p4_16_samples/default-package-argument.p4(22): error: main: No argument for parameter c
P() main;
    ^^^^
/Users/hanwang/p4c/testdata/p4_16_samples/default-package-argument.p4(17)
package P<H, M>(C<H, M> c = nothing());
                        ^
```

```
struct intrinsic_metadata_t {
   bit<8> f0;
   bit<8> f1;
}

struct empty_t {}

control nothing(inout empty_t hdr, inout empty_t meta, in intrinsic_metadata_t imeta) {
   apply {}
}

control C<H, M>(
    inout H hdr,
    inout M meta,
    in intrinsic_metadata_t intr_md);

package P<H, M>(C<H, M> c = nothing());

struct hdr_t { }
struct meta_t { }

P() main;
```

**Comment by jafingerhut** [comment] 2019-04-30 01:01
Probably a duplicate issue, with a somewhat different example program that would be nice if it would compile attached as an example, here: https://github.com/p4lang/p4c/issues/1914

**Comment by mbudiu-vmw** [comment] 2019-08-07 22:29
I cannot reproduce this bug. It seems to have been solved by some commit.
I will mark as fixed and possibly close it later if no one objects.

**Closed** 2020-05-28 23:34 UTC
Labels: bug, fixed
