### ISSUE TITLE
Bug [Simple_switch]: register_array is empty or duplicate.

### ISSUE THREAD

**Issue by qin-nz** [p4lang/p4c#1097] opened 2017-12-13 03:00 UTC
Hi,
I want to make a register available both in ingress and egress. So I declare it out of control.
The result json for bmv2 might be wrong.

`"register_arrays" : [],`

And this will lead to bmv2 quit unexpectedly. 
https://github.com/p4lang/behavioral-model/issues/492

Source code is following.
```
#include <core.p4>
#include <v1model.p4>

struct Headers {}

struct Meta {}

parser p(packet_in b, out Headers h, inout Meta m, inout standard_metadata_t sm) {
    state start {
        transition accept;
    }
}

register<bit<8>>(2) r;

control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    apply {
        bit<8> x;
        r.read(x,0);
    }
}

control vrfy(inout Headers h, inout Meta m) { apply {} }
control update(inout Headers h, inout Meta m) { apply {} }
control egress(inout Headers h, inout Meta m, inout standard_metadata_t sm) { apply {} }
control deparser(packet_out b, in Headers h) { apply {} }

V1Switch(p(), vrfy(), ingress(), egress(), update(), deparser()) main;
```

**Comment by qin-nz** [comment] 2017-12-13 03:56
Another example can make  `register_array` has duplicate register.

```
#include <core.p4>
#include <v1model.p4>

struct H {}
struct M {}
parser p(packet_in b, out H h, inout M m, inout standard_metadata_t sm) {
    state start {
        transition accept;
    }
}
control ingress(inout H h, inout M m, inout standard_metadata_t sm) {
    register<bit<8>>(2) r;
    apply {
        bit<8> x;
        r.read(x,0);
    }
}
control egress(inout H h, inout M m, inout standard_metadata_t sm) {
    register<bit<8>>(2) r;
    apply { 
        bit<8> y;
        r.read(y,0);} 
    }
control vrfy(inout H h, inout M m) { apply {} }
control update(inout H h, inout M m) { apply {} }
control deparser(packet_out b, in H h) { apply {} }

V1Switch(p(), vrfy(), ingress(), egress(), update(), deparser()) main;
```

**Comment by jafingerhut** [comment] 2017-12-13 15:42
Your second example, with duplicate names in the bmv2 JSON file because of using the same instance name in both ingress and egress, is not unique to register instances, but is a problem for all kinds of instances that have the same name and are instantiated in both ingress and egress in P4_16 programs.  That issue is covered by #1073 and/or #486.

Your first example does produce an erroneous bmv2 JSON file with the latest p4c-bm2-ss as of 2017-Dec-13, erroneous because there are references to a register_array that is not defined in the "register_arrays" key of the JSON file.  However, realize that I believe Mihai Budiu has commented in another issue that such externs instantiated at the top level may not be supported in p4c-bm2-ss, and a fix in this case might be to modify the compiler to give an error for the first program because of trying to use the same top-level instance from both ingress and egress.

Why, you may reasonably ask?  Because some high performance P4 targets won't allow that, either, and simple_switch is intended by design to have some of those restrictions as well.  While it would be possible to write a software P4 switch without those restrictions, I believe it may sometimes be considered a good property that it can let you know early about such things, before making mistaken assumptions that your P4 program will work when written a certain way on a high performance target.

**Comment by mbudiu-vmw** [comment] 2017-12-13 16:28
That is correct, these are two separate bugs, but they are both duplicates of existing bugs.

**Comment by antoninbas** [comment] 2017-12-13 17:26
@jafingerhut there is no such limitation in bmv2 AFAIK
The `register_arrays` list in the JSON is global and any register array can be accessed from all pipelines & all parsers.

**Comment by mbudiu-vmw** [comment] 2017-12-13 17:27
In this case we can probably solve issue #696.

**Comment by antoninbas** [comment] 2017-12-13 17:38
[global_register_test.json.txt](https://github.com/p4lang/p4c/files/1556410/global_register_test.json.txt)

@mbudiu-vmw I'm not sure. I don't think the bmv2 **backend** is producing the correct JSON. Issue #696, of which this issue is a duplicate still exists according to @qin-nz and @jafingerhut . The backend produces a JSON with an empty `register_arrays` list (but multiple reference to register arrays in action code), which is causing bmv2 to crash. IMO, it should be producing a JSON similar to the one attached.

**Comment by mbudiu-vmw** [comment] 2017-12-13 17:40
I didn't mean we can close the issue, I meant that we can implement a fix for the issue.
That's still to be done.

**Comment by antoninbas** [comment] 2017-12-13 17:42
@mbudiu-vmw yes that's correct, sorry I misunderstood
Yes there is nothing standing in the way of supporting this in p4c-bm2-ss

**Comment by qin-nz** [comment] 2017-12-14 09:25
Thanks @jafingerhut .

@antoninbas Maybe we should throw a warning when sharing a register.

**Comment by mbudiu-vmw** [comment] 2017-12-15 17:33
I have sent a PR which fixes the first part of this problem, which duplicates #696.
The second part, about the duplicated names will be fixed later.
But I think we can close this after the PR is accepted.

**Closed** 2018-01-02 17:50 UTC
Labels: duplicate, fixed
