### ISSUE TITLE
BMv2 target segfault

### ISSUE THREAD

**Issue by jadedeane** [p4lang/p4c#2082] opened 2019-11-12 03:59 UTC
Using p4c 1.2.0 and macOS 10.15.1. Despite compiling seemingly completing without issue there was no JSON file:

```
$p4c --target bmv2 --arch v1model --std p4-16 --p4runtime-format json --p4runtime-files reference_application.txt reference_application.p4 -v
running cc -E -C -undef -nostdinc -x assembler-with-cpp -I /usr/local/share/p4c/p4include -o ./reference_application.p4i reference_application.p4
running /usr/local/bin/p4c-bm2-ss -I /usr/local/share/p4c/p4include --p4v=16 --p4runtime-files reference_application.txt -o ./reference_application.json ./reference_application.p4i --arch v1model

$ls -al reference_application.*
-rw-r--r--  1 jdeane  staff   4855 Nov 11 19:28 reference_application.p4
-rw-r--r--  1 jdeane  staff  36207 Nov 11 19:43 reference_application.p4i
-rw-r--r--  1 jdeane  staff    771 Nov 11 19:43 reference_application.txt
```

Running `p4c-bm2-ss` directly, I noticed there was a segfault:

```
$/usr/local/bin/p4c-bm2-ss -I /usr/local/share/p4c/p4include --p4v=16 --p4runtime-files reference_application.txt -o ./reference_application.json ./reference_application.p4i --arch v1model
[1]    77293 segmentation fault  /usr/local/bin/p4c-bm2-ss -I /usr/local/share/p4c/p4include --p4v=16   -o
```

`p4c-bm2-ss` verbose detail: https://gist.github.com/jadedeane/93c5742424c8d91165c2a1af3c45a66c

Thanks in advance for help and guidance.

**Comment by jafingerhut** [comment] 2019-11-12 04:30
If you are able to share your P4_16 source code reference_application.p4 (and any other files it #include's) publicly, I'd be happy to test whether a similar problem occurs when running p4c on a Linux VM.

Whether you are able to share it or not, if you are willing to install a Linux VM on your Mac (I'm happy to provide a few instructions if you haven't done so before), you could see if the problem exists on that platform, too.

**Comment by jadedeane** [comment] 2019-11-12 04:49
Thanks for the quick reply.

While I'm unable to share the source, using the tutorial's basic forwarding (solution) code reproduces the issue.

Not opposed to attempting a Linux-based build at all, as I'd assume this problem is related to either macOS or my p4c build attempt itself.

As an aside, I went back and looked at the build logs and found this:

```
-- Program 'simple_switch_CLI' (https://github.com/p4lang/behavioral-model.git) not found;
Searched .
Will not run BMv2 tests. (missing: SIMPLE_SWITCH SIMPLE_SWITCH_CLI)
-- Program 'psa_switch_CLI' (https://github.com/p4lang/behavioral-model.git) not found;
Searched .
Will not run PSA BMv2 tests. (missing: PSA_SWITCH PSA_SWITCH_CLI)
```

I found it odd that failed, as the p4c repo was cloned recursively, and what I assume are the correct files are within `backends/bmv2`:

```
ls -al backends/bmv2
total 80
drwxr-xr-x  12 jdeane  staff    384 Nov 11 20:29 .
drwxr-xr-x   6 jdeane  staff    192 Nov 11 20:29 ..
drwxr-xr-x   8 jdeane  staff    256 Nov 11 20:29 CMakeFiles
-rw-r--r--   1 jdeane  staff    289 Nov 11 20:29 CTestTestfile.cmake
-rw-r--r--   1 jdeane  staff  14452 Nov 11 20:29 Makefile
-rw-r--r--   1 jdeane  staff   2079 Nov 11 20:29 cmake_install.cmake
drwxr-xr-x   3 jdeane  staff     96 Nov 11 20:29 psa_switch
drwxr-xr-x   3 jdeane  staff     96 Nov 11 20:29 simple_switch
-rw-r--r--   1 jdeane  staff    430 Nov 11 20:29 unified_bmv2_backend_common_srcs_1.cpp
-rw-r--r--   1 jdeane  staff    395 Nov 11 20:29 unified_bmv2_backend_common_srcs_2.cpp
-rw-r--r--   1 jdeane  staff    344 Nov 11 20:29 unified_bmv2_psa_switch_srcs_1.cpp
-rw-r--r--   1 jdeane  staff    368 Nov 11 20:29 unified_bmv2_simple_switch_srcs_1.cpp
```

Complete build logs here: https://gist.github.com/jadedeane/eb2c1422c8aefa8eb9470cd308258042

**Comment by jafingerhut** [comment] 2019-11-12 05:00
I am not certain, but I believe that those messages you point out were because you installed p4c without first installing the behavioral-model.  If you install the behavioral-model repository code before installing p4c, it enables more of p4c's included tests to be run.  I doubt that those messages are causing the seg fault problem you are experiencing while running p4c.

If you don't mind spending 20 Gybtes or so for an Ubuntu 16.04 or 18.04 Linux system, and about 60 to 90 minutes building not only p4c, but also protobuf, behavioral-model, etc. on it, this shell script can potentially save you the hassle of poring through all of the READMEs of each project to get their install instructions correct: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

Sorry, I do not have a similarly well-tested script for macOS.

**Comment by jafingerhut** [comment] 2019-11-12 05:30
Also, I have tested the tutorials basic.p4 (the solutions) version on both an Ubuntu 16.04 and 18.04 Linux VM, after using the script I linked instructions for above, with no errors.

**Comment by jadedeane** [comment] 2019-11-12 17:32
That's a really great script. I did however go a slightly different way, namely using a container for the build environment, and everything compiled just fine. Works well for both local development, and CI/CD pipeline use.

Given macOS isn't officially supported I imagine this issue can die, although I'm happy to help sort macOS specifics if there are cycles to spend.

Thanks again for your time.

**Comment by mbudiu-vmw** [comment] 2019-11-12 18:02
Perhaps you can run this under gdb and give us a stack trace at the point where it crashes?

**Comment by mbudiu-vmw** [comment] 2019-11-13 17:57
I don't think we have enough information to reproduce this issue. I will close it, but we can reopen if needed.

**Closed by mbudiu-vmw** 2019-11-13 17:57 UTC
